### ISSUE TITLE
File name is longer than the maximum allowed path length on this platform

### ISSUE THREAD

**Issue by Daml** [KnpLabs/snappy#116]
Passing large html string to $options['header-html'] & $options['footer-html'] cause handleOptions() to check if those options are uris or files before fallback on creatingTemporaryFile().

This call AbstractGenerator:isFile(), and so php's is_file() with strings which can be too large for many filesystem defaults. Response is false as expected but emit a warning.

We can check for string length in Pdf.php, or in AbstractGenerator.php, or simply ignore the warning.

**Comment by wouterbulten** [comment]
I had the same problem. PR was submitted.

For now I use the following approach to monkey-patch the problem:

```php
use Knp\Snappy\Pdf as SnappyPdf;

class Pdf extends SnappyPdf {

    public function isFile($filename) {
        return strlen($filename) <= PHP_MAXPATHLEN && parent::isFile($filename);
    }
}

```
