### ISSUE TITLE
CSS support for box-sizing: border-box

### ISSUE THREAD

**Issue by austenc** [KnpLabs/snappy#133]
This is more of a question than an issue really but I figured this was the best place to ask.

Does snappy support css `box-sizing: border-box`? I was hoping to use that property to lay out a page that needs to be precisely printed but it seems to be falling back to `box-sizing: content-box` when the pdf is generated. 

I'm using snappy with laravel, via barryvdh/laravel-snappy, I installed it yesterday so I assume everything is pretty up-to-date.

Thanks in advance!

**Comment by pilot** [comment]
`box-sizing` should be supported by http://wkhtmltopdf.org, there is not the case of snappy lib.

- check that you use latest `wkhtmltopdf` version 
- try to generate pdf from html directly from the command line to be sure that pdf is generated **Ok**, but with snappy you get the problem.

**Comment by austenc** [comment]
Thanks for the explanation, will do!
