### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by Yeldos** [KnpLabs/snappy#135]
I'm getting error when I try to use snappy code. What is the reason? My folder is set to write permission.

My code is like this:

if(file_exists("Knp/Snappy/Pdf.php"))
{
    include_once("Knp/Snappy/Pdf.php");
}
else
{
    echo "no such PDF.php file";
    exit;	
}

$snappy = new Pdf();

$binary_64    = "$s_root/my_folder/wkfromhtmltopdf/wkhtmltopdf-amd64";
$binary_32    = "$s_root/my_folder/wkfromhtmltopdf/wkhtmltopdf-i386";

$binary = $binary_64;   
 
if(file_exists($binary)){
    echo $snappy->setBinary($binary);
}else{
	echo "no such binary";
	exit;	
}

header('Content-Type: application/pdf');
header("Content-Disposition: attachment; filename='test.pdf'";

$snappy->setOption('enable-javascript', true);
$snappy->setOption('javascript-delay',13500);
$snappy->setOption('enable-smart-shrinking', true);
$snappy->setOption('no-stop-slow-scripts', true);

echo $snappy->getOutput(array('http://www.github.com','http://www.knplabs.com','http://www.php.net'));

if(file_exists($source)){
    echo $snappy->getOutput($source);
}else{
    echo  "No File";
    exit;
}

**Comment by willpower232** [comment]
You should turn on error reporting in your PHP configuration to see what is wrong.
I believe your problem is probably here:
```
echo $snappy->setBinary($binary);
```
As you are echo'ing something, you are sending headers and output to the screen so you cannot set more headers after this point. Presumably you do not need to echo this line at all?

**Comment by Yeldos** [comment]
@willpower232 Thank you for your answer, I turned on my php reporting and I'm getting this error:

[19-Jan-2015 04:03:54] PHP Warning:  shell_exec() has been disabled for security reasons in /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/Knp/Snappy/AbstractGenerator.php on line 365
[19-Jan-2015 04:03:54] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The file '/tmp/knp_snappy54bc822a6b038.pdf' was not created (command: /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/wkhtmltopdf-amd64 --lowquality --enable-javascript --enable-smart-shrinking --no-stop-slow-scripts "http://tests.katev.kz/soru_bankasi/cquiz/print-quizzes.php?qid=1690&columnNumber=2&qname=abs" "/tmp/knp_snappy54bc822a6b038.pdf").' in /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/Knp/Snappy/AbstractGenerator.php:267
Stack trace:
#0 /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/Knp/Snappy/AbstractGenerator.php(123): AbstractGenerator->checkOutput('/tmp/knp_snappy...', '/home/katevkz/p...')
#1 /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/Knp/Snappy/AbstractGenerator.php(145): AbstractGenerator->generate('http://tests.ka...', '/tmp/knp_snappy...', Array)
#2 /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/create-pdf.php(77): AbstractGenerator->getOutput('http://tests.ka...')
 in /home/katevkz/public_html/tests/soru_bankasi/wkfromhtmltopdf/Knp/Snappy/AbstractGenerator.php on line 267

By the way I've changed a little bit my code, but it's not so important. The problem is that when I run the command from console, everything works great, the file is created in /tmp, but on the site, when I click on a file button, it doesn't create a file.

**Comment by Yeldos** [comment]
Solved this problem by enabling shell_exec and escapeshellarg in php.ini. But in security reason it's not safe, do anybody know other way of doing this?

**Comment by akovalyov** [comment]
@Yeldos [safe mode](http://php.net/manual/en/features.safe-mode.php) is deprecated in PHP5.3 and removed in PHP5.4. In the description there is an explanation of why this safe mode was introduced and why it is incorrect.
