### ISSUE TITLE
wkhtmltopdf  The exit status code '135' 

### ISSUE THREAD

**Issue by ahmedwafdi** [KnpLabs/snappy#141]
Hello world 
I'm using static version of 'wkhtmltopdf' i have upload my project on a FTP server but i have a problem when  i want to generate the PDF 
this is my exception :-1: 

![image](https://cloud.githubusercontent.com/assets/7659573/6358146/739631de-bc61-11e4-92ce-8d925843866a.png)

**Comment by pilot** [comment]
there's `wkhtmltopdf` exit status code, snappy just response with it, you should be sure that `wkhtmltopdf` works on the your server, to test it from the command line, or ask support if you have not access to the command line

**Comment by ahmedwafdi** [comment]
no it's work good in server but i'dont know why he doesn't work this time

**Comment by akovalyov** [comment]
Bus error is not snappy fault. It seems that wkhtmltopdf has no permission to access memory it tries to read.
Reference - http://stackoverflow.com/questions/212466/what-is-a-bus-error
