### ISSUE TITLE
Exception when generating multiple PDFS in Ubuntu 14.04

### ISSUE THREAD

**Issue by gustavomanolo** [KnpLabs/snappy#146]
The exit status code '1' says something went wrong:
stderr: "xvfb-run: error: Xvfb failed to start
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality '/tmp/knp_snappy5509fb36a770b1.09134752.html' '/home/facti/www/www/tmp/pdfinv_5509fb36a74047.12759336.pdf'.))

Do you know why i'm getting this error?

**Comment by akovalyov** [comment]
@gustavomanolo please, check https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#q-it-says-wkhtmltopdf-cannot-connect-to-x-server-or-xvfb-run-error-xvfb-failed-to-start
