### ISSUE TITLE
Multiple URLs creates broken PDF

### ISSUE THREAD

**Issue by webberdesign** [KnpLabs/snappy#147]
Snappy works for a single page url output, however when I try to add the output array of more than one, the PDF is created however does not open.   Any ideas?

**Comment by silasrm** [comment]
This function is broken. PDF contain content of 1 URL, not all.

**Comment by akovalyov** [comment]
Just checked it.

```php
require __DIR__ . '/vendor/autoload.php';

use Knp\Snappy\Pdf;

$snappy = new Pdf('/home/andrew/.composer/vendor/bin/wkhtmltopdf-amd64');
file_put_contents('multiple.pdf', $snappy->getOutput(['http://www.github.com', 'http://google.com']));
```
works like a charm.
Please, check the API and your usage.

**Comment by webberdesign** [comment]
Multiple urls into a multipage pdf not just a multipage pdf.  Must need a ton of server resources to work.

**Comment by akovalyov** [comment]
Not sure if I got the idea. Do you have the code example which Snappy handles in incorrect way?
