### ISSUE TITLE
One Document with Multiple Orientations

### ISSUE THREAD

**Issue by Johnb21** [KnpLabs/snappy#148]
I currently have a single twig file that is including 5 different twig files in order to print one single file on the click of a link,

Everything works fine until I add tables that are required in the print. Trying to use CSS

    @media print{
        @page{
            size: letter landscape;
       }

    ... more CSS
    }

fails to load the CSS at all so that option is out. I would like to know if there is an option/method to set the orientation of specific pages instead of applying it to the entire PDF when it is created. Or is there a way I can create the regular pages with Portrait, Create the page I need in landscape and then merge them together as one document?

**Comment by akovalyov** [comment]
@Johnb21 sorry I got to you so lately, but anyway it is better than never. 
I see two possible solutions here. First one is to render 5 individual pdf files and then merge it via any pdf util like `pdfunite`, `pdftk` or whatever.
Another possible solutions is to wrap your html in divs, i.e.

```html
<div class="portrait">
<!--some portrait page content-->
</div>
</div class="landscape">
<!--some landscape page-->
</div>
<style type="text/css" media="print">
    .landscape
    {
     -webkit-transform: rotate(-90deg); 
    }
</style>
```

However, it is not related to Snappy itself at all.

**Comment by ahmed-bhs** [comment]
@akovalyov wrap your html in divs, didn't work for me :/
