### ISSUE TITLE
wkhtmltopdf command not finding assets

### ISSUE THREAD

**Issue by liquorvicar** [KnpLabs/snappy#159]
We are using snappy via the Sylius project and getting an error every time we try and view a PDF:
[2015-05-21 10:55:52] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [>                                                           ] 0% 
[======>                                                     ] 10% 
[=======>                                                    ] 12% 
Warning: Failed to load file:///web/assets/compiled/frontend.js (ignore) Warning: Failed to load file:///web/js/create.js (ignore) Warning: Failed to load file:///web/js/hallo-extra.js (ignore) [=========>                                                  ] 15% 
[================>                                           ] 28% [============================================================] 100%
Counting pages (2/6)                                                [============================================================] 
Object 1 of 1 Resolving links (4/6)                                                        [============================================================]
 Object 1 of 1 Loading headers and footers (5/6)                                            
Printing pages (6/6)
[>                                                           ] Preparing [============================================================] 
Page 1 of 1 Done                                                                       
Exit with code 1 due to network error: ProtocolInvalidOperationError " stdout: "" command: /usr/local/bin/wkhtmltopdf --lowquality --footer-font-name '"Helvetica Neue",Helvetica,Arial,sans-serif' --footer-font-size '10' --footer-left '[title]' --footer-line --footer-right '[page]/[topage]' '/tmp/knp_snappy555daba8451471.13264624.html' '/tmp/knp_snappy555daba8451f79.95635999.pdf'." at /path/to/project/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php line 333 {"exception":"[object] (RuntimeException(code: 0): The exit status code '1' says something went wrong:\n
stderr: \"Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[=======>                                                    ] 12%
Warning: Failed to load file:///web/assets/compiled/frontend.js (ignore)
Warning: Failed to load file:///web/js/create.js (ignore)
Warning: Failed to load file:///web/js/hallo-extra.js (ignore)
[=========>                                                  ] 15%
[================>                                           ] 28%
[============================================================] 100%
Counting pages (2/6)   
[============================================================] Object 1 of 1
Resolving links (4/6)                                                       
[============================================================] Object 1 of 1
Loading headers and footers (5/6)                                           
Printing pages (6/6)
[>                                                           ] 
Preparing
[============================================================] Page 1 of 1
Done                                                                      
Exit with code 1 due to network error: ProtocolInvalidOperationError
\"\nstdout: \"\"\ncommand: /usr/local/bin/wkhtmltopdf --lowquality --footer-font-name '\"Helvetica Neue\",Helvetica,Arial,sans-serif' --footer-font-size '10' --footer-left '[title]' --footer-line --footer-right '[page]/[topage]' '/tmp/knp_snappy555daba8451471.13264624.html' '/tmp/knp_snappy555daba8451f79.95635999.pdf'. at /path/to/project/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:333)"}

Not quite sure where to look to work out what the problem is. Any ideas?

**Comment by docteurklein** [comment]
Yep, your asset urls need to be absolute.

This can be accomplished in symfony using the `asset` twig funtion and "package urls":

http://symfony.com/doc/current/reference/configuration/framework.html#assets-base-urls

**Comment by liquorvicar** [comment]
Ok, thanks for the info; sounds like it's a Sylius issue. Will dig into the templates.

**Comment by docteurklein** [comment]
not really a sylius problem, just your config of FreameworkBundle.

**Comment by docteurklein** [comment]
unless the (default) templates don't use the `asset` function, in which case you're still able to everride the one that needs it.

**Comment by liquorvicar** [comment]
Thanks for the help. Managed to get past that error. Got another one now but I think it might be SymfonyCmf related:
https://github.com/symfony-cmf/CreateBundle/issues/138
