### ISSUE TITLE
Strange encoding after upgrading

### ISSUE THREAD

**Issue by cmodijk** [KnpLabs/snappy#162]
I just upgraded from `0.3.3` to `0.4` and the encoding of my PDF is know very strange. After debugging i noticed that when i change the f29edc4e53429deec2b394926a8f743a0ad2e28e commit back it works like a charm again. 

![Strange encoding](https://cloud.githubusercontent.com/assets/771041/8210950/c9c7667a-1514-11e5-9391-cb537722840d.png)
![schermafbeelding 2015-06-17 om 17 13 43](https://cloud.githubusercontent.com/assets/771041/8210951/c9c7f6ee-1514-11e5-8e17-0c52fdad9f53.png)

**Comment by akovalyov** [comment]
@cmodijk wow. Could you paste your configuration for snappy here, please?

**Comment by cmodijk** [comment]
I'm using the `KnpSnappyBundle` and have no settings.

**Comment by akovalyov** [comment]
@cmodijk OK, I have retested snappy with the latest release and found no issues neither with English not with Dutch(you are using Dutch, right?) language and PDF rendering. 
What I have noticed is that there are some pictures, it is not ASCII symbols. I'd say it is either an issue with webfonts or with fonts installed on your server (since I do not see any connection between your issue and https://github.com/KnpLabs/snappy/commit/f29edc4e53429deec2b394926a8f743a0ad2e28e).

**Comment by docteurklein** [comment]
as always, there are big chances the issue is directly related to wkhtmlo, not snappy. try the same by invoking wkhtml on the command line.

**Comment by cmodijk** [comment]
I just tested the 2 versions and dumped the commands that where executed which both look exactly the same and both work perfect. But running the same commands trough snappy are like my first screen. Looks like it have something to do with the env setting but i don't onderstand what. 

Command from 0.3
```
wkhtmltopdf --lowquality '/tmp/knp_snappy5589a9c5effda7.89683686.html' '/tmp/knp_snappy5589a9c5f01375.26037744.pdf'
```

Command from 0.4
```
wkhtmltopdf --lowquality '/tmp/knp_snappy5589aa81316314.20585604.html' '/tmp/knp_snappy5589aa81317fa0.63863890.pdf'
``

**Comment by cmodijk** [comment]
I just added some dump calls the proc_open command from the symfony/process class but those seems to do the exact same thing.. I'm really confused know.

**Comment by cmodijk** [comment]
I also reported an issue at https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2426

**Comment by cmodijk** [comment]
Just like i thought wkhtmltopdf can't help me.

**Comment by docteurklein** [comment]
@cmodijk ok, if the commad line works fine, then it's not a wkhtml problem.
I'm not sure how to work this out, but you can try to compare the html output you give to snappy and see if it doesn't contains strange encoding.

**Comment by rpestana** [comment]
Hi!
I had the same problem.
Do this on you server (if it is a CentOS): yum install urw-fonts

**Comment by akovalyov** [comment]
@cmodijk has answer of @rpestana helped you? If so, I'd want to put it into troubleshooting section.

**Comment by cmodijk** [comment]
Tnx @rpestana it's fixed!
