### ISSUE TITLE
Secure pdf?

### ISSUE THREAD

**Issue by robgavina** [KnpLabs/snappy#164]
Is there a way to secure the pdf so it can't be edited?  I am currently streaming the pdf content to the end user's browser.

Thanks for any help.

**Comment by pilot** [comment]
there is no way to secure the pdf file, you can check the oficial manual http://wkhtmltopdf.org/usage/wkhtmltopdf.txt

**Comment by akovalyov** [comment]
@robgavina, there is no way to add a password via wkhtmltopdf, but there is a way via other linux tools like (pdftk)[http://askubuntu.com/a/258867]
But in this case you will need to dump file somewhere to be able to secure it. Also there were some php approaches to add a password but I am not aware of it.
