### ISSUE TITLE
Symfony\Component\Process\Exception\ProcessTimedOutException on PDF generation

### ISSUE THREAD

**Issue by sn0opr** [KnpLabs/snappy#169]
I'm using Laravel Snappy package, and I think the problem is from Snappy itself.
In my localhost (Windows 7 32bit) `wkhtmltopdf 0.12.2.3 (with patched qt)` everything is working fine.
In the deployment machine (Windows Server 2012 R2 64bit) `wkhtmltopdf 0.12.2.4 64bit`, it takes about 60 seconds without any response or error... Good news I'm using Bugsnag service to track bugs and errors, and this is what I get:
`Symfony\Component\Process\Exception\ProcessTimedOutExceptionGET /gca/public/demandes-achat/1138/pdf
The process "C:\xampp\htdocs\gca/wkhtmltopdf/bin/wkhtmltopdf.exe --lowquality "C:\Windows\TEMP\knp_snappy55a4f9ff7f5862.10272127.html" "C:\Windows\TEMP\knp_snappy55a4f9ff7fab55.21457299.pdf"" exceeded the timeout of 60 seconds.`
But when I tested to generate pdf from a website like google, it works fine !, with a plain html it wroks fine too.
I'm getting crazy here because it's working on my dev machine Win 7 and my computer Win 8.1 with difference wkhtmltopdf version for sure...

Btw, I'm using Bootstrap.min.css and Fontawesome.css

Please help me it's urgent.

**Comment by akovalyov** [comment]
@sn0opr I have good news and bad news for you. 
Good news is that we are here to help
Bad news is that we can not.
60 seconds is default timeout for Symfony/Process. Your error means that in 60 seconds there was no response from wkhtmltopdf. In this case the only thing is possible - networking issues. Generating pdf from local html or google website will work since it is loaded fastly. Please, check the url which you are trying to fetch. And remember that not only the html itself should be loaded in 60 seconds but all the resources which that html contains. 
If you just want to increase the timeout - you can set it here - https://github.com/KnpLabs/snappy/blob/3aaabad8bb36a9fbca275407874eed28f406fe24/src/Knp/Snappy/AbstractGenerator.php#L102. If you want to do that - please, consider that you use the latest snappy version. 
Cheers.

**Comment by docteurklein** [comment]
@sn0opr My guess is that it comes from wkhtmltopdf, not snappy.
You should try to execute the **exact same** command that the application generates (look at the logs or var_dump it in AbstratGenerator), and try to execute it in a shell, on the production server.

**Comment by sn0opr** [comment]
@akovalyov Hi, thank you for the fast reply.

1 - I'm generating pdf from local resources
2 - I'm only loading 3 css files (bootstrap.min.css, fontawesome.min.css and a small css file that made for my pdf pages)
3 - @docteurklein  I tried the ```wkhtmltopdf.exe``` program using the command line and it works like expected, I uses the same html page and It converts in about 2 seconds not more.

4 - I removed the css files from the <head> to try if the resources are making the issue, and yeah It worked, but without any css file.. Now I'm confused..., how it works with command line without any issue but not with the Snappy class.

5 - I tried the Symfony class ```Symfony\Component\Process\Process``` and run the command myself ```, same thing, it's not working in Windows Server 2012 but it works in Win 7 and Win 8! :
```
$binary = \Config::get('snappy.pdf.binary');
    $process = new Symfony\Component\Process\Process($binary.' '.url('demandes-achat/1024/pdf').' test.pdf');
    $process->run(function ($type, $buffer) {
        if (\Symfony\Component\Process\Process::ERR === $type) {
            echo 'ERR > '.$buffer;
        } else {
            echo 'OUT > '.$buffer;
        }
    });
```

**Comment by docteurklein** [comment]
Interesting: So it's definitly a problem with the Process execution. You can try to find existing issues on https://github.com/symfony/symfony/issues?q=is%3Aopen+is%3Aissue+label%3AProcess

**Comment by akovalyov** [comment]
@sn0opr have you tried to execute wkhtmltopdf command manually in Windows cmd?

**Comment by sn0opr** [comment]
@akovalyov Like I said, yes I did and it's works perfectly, I changed my pdf script from returning pdf file with Snappy to returning html file and tested with command line, it dose the job in a very small time. here is the output:

```
PS C:\xampp\htdocs\gca\wkhtmltopdf\bin> .\wkhtmltopdf.exe http://localhost/gca/public/demandes-achat/1138/pdf processs.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

**Comment by docteurklein** [comment]
@sn0opr you can try to narrow the problem:

try with php -a:

    require 'vendor/autoload.php';
    proc_open($cmd,
        array(
            array("pipe","r"),
            array("pipe","w"),
            array("pipe","w")
        ),
    $pipes);

**Comment by sn0opr** [comment]
@docteurklein thank you for trying to help me,
I just tried with the native php ```exec()``` method and It worked like expected!!! 
So the problem is from the ```Symfony\Component\Process\Process``` class !

```
//var_dump(exec($binary.' http://localhost/gca/public/demandes-achat/1138/pdf rihane.pdf'));
//exec method works fine and outputs the file like expected
	proc_open($binary.' http://localhost/gca/public/demandes-achat/1138/pdf rihane.pdf',
    array(
        array("pipe","r"),
        array("pipe","w"),
        array("pipe","w")
    ),$pipes);
	var_dump($pipes);
```
result: 
```array(3) { [0]=> resource(86) of type (Unknown) [1]=> resource(87) of type (Unknown) [2]=> resource(88) of type (Unknown) }```

**Comment by docteurklein** [comment]
for proc open, you should use:

    var_dump(array_map('stream_get_contents', $pipes));

Also, proc_open doesn't return anything, but you can still look at the file rihane.pdf and see if it worked.

**Comment by docteurklein** [comment]
So, if proc_open fails, then it's a problem with php's http://php.net/proc_open.
You can try to search for solutions there.

**Comment by docteurklein** [comment]
For example: http://php.net/manual/en/function.proc-open.php#97012

**Comment by sn0opr** [comment]
@docteurklein sorry for the late, I tested with array_map function and I got an error:

```
$binary = \Config::get('snappy.pdf.binary');
	proc_open($binary.' http://localhost/gca/public/demandes-achat/1138/pdf xxx.pdf',
    array(
        array("pipe","r"),
        array("pipe","w"),
        array("pipe","w")
    ),$pipes);
	var_dump(array_map('stream_get_contents', $pipes));
```
Output : 
```
stream_get_contents(): 86 is not a valid stream resource

**Comment by sn0opr** [comment]
@docteurklein @akovalyov , I just found a solution.
I got to the source code of Snappy package and found in the **AbstractGenerator::executeCommand()** method that you use your own Process class if Symfony Process class dosen't exist, so I just remove this condition and used Snappy's Process class, and it worked like a charm!:
```
protected function executeCommand($command)
    {
        /*if (class_exists('Symfony\Component\Process\Process')) {
            $process = new \Symfony\Component\Process\Process($command, NULL, $this->env);
            if ($this->timeout !== false) {
                $process->setTimeout($this->timeout);
            }
        } else {
            $process = new Process($command, $this->env);
        }*/

        $process = new Process($command, $this->env);
        $process->run();

        return array(
            $process->getExitCode(),
            $process->getOutput(),
            $process->getErrorOutput(),
        );
    }
```

Can you please provide an option to use Symfony's Process class or the default one ?.
Thank you for the support

**Comment by docteurklein** [comment]
see #166

**Comment by akovalyov** [comment]
@sn0opr you can install it as `dev-master` if you use composer

**Comment by osaris** [comment]
I don't get the point, looks like @sn0opr say that it works with the Process class from snappy and you removed it in #166 to force usage of the one from Symfony ?

I have the same problem and using 0.4 and forcing to use the snappy Process class works for me.

**Comment by akovalyov** [comment]
@osaris thank for the feedback. Could you give a little bit more of details about the environment and the input options for Snappy? For how many iterations have you launched it? 
I will setup a test env later this week on Linux to see an compare the execution time.

@jeremyb do you still have Windows env to test the Snappy performance with  Symfony/Process? :)

**Comment by osaris** [comment]
@akovalyov on my dev machine (OSX), on 5 runs with the same HTML to convert to PDF the time is very similar. 

On our production environment (Windows 2008 R2, Apache 2.4, PHP 5.6.10, Laravel 5.1), I need to remove the css link to have it working with Symfony2 Process (it's ok with Snappy Process class), but the results are very different, on 10 runs with Snappy Process class, I have an average of 561ms to get the PDF, with Symfony2 Process class I have 2.61 seconds !!

Despite the performance issue, my main problem is that I can't use css link If I use the Symfony2 Process class but it's ok with Snappy Process class.

**Comment by pilot** [comment]
+1 to have abiltiy to chose type of processor, symfony or native

**Comment by sn0opr** [comment]
+1

**Comment by docteurklein** [comment]
Interesting. We removed the embedded Process class because iti didn't work well on many setups.
And I really think we should leverage a well tested library like Symfony's Process, even tho it seems to not work in some cases.

The best would be to concentrate on fixing it, not snappy.

**Comment by osaris** [comment]
@docteurklein make sense for me, the related issue on symfony part seems to be this one : https://github.com/symfony/symfony/issues/15278

**Comment by docteurklein** [comment]
BTW, you could try to put enhanceWindowsCompatibility to false, just to try.

**Comment by osaris** [comment]
@docteurklein can I change this setting in my snappy configuration file or somewhere else in my app ?

**Comment by akovalyov** [comment]
@osaris @docteurklein is talking about https://github.com/symfony/symfony/blob/5f36605e0e2264a1f52a8caa4bbe35a6f4ece8b4/src/Symfony/Component/Process/Process.php#L1174.

You can also try to experiment with `bypass_shell: false` and `supress_errors: true` (you can set it via https://github.com/symfony/symfony/blob/5f36605e0e2264a1f52a8caa4bbe35a6f4ece8b4/src/Symfony/Component/Process/Process.php#L1148)

**Comment by osaris** [comment]
Sorry for the delay. 

enhanceWindowsCompatibility don't change anything. Same for bypass_shell and supress_errors.

**Comment by WouterSioen** [comment]
I have the same issue with the process component (see https://github.com/symfony/symfony/issues/15278#issuecomment-156370152)

It would be awesome to be able to choose the old Snappy Process class instead of the Symfony Component.

**Comment by WouterSioen** [comment]
I only have this issue when I pass on my PHPSESSID cookie to the process.

```
$this->snappy->setOption(
    'cookie',
    [ 'PHPSESSID' => $this->request->cookies->get('PHPSESSID') ]
);
```

The generated pdf is correct though. It's just the Symfony Process that isn't stopping with this option.
I guess this means that it's a wkhtmltopdf issue?

I don't know why the Symfony Process fails on it though.

**Comment by WouterSioen** [comment]
Hmm, it seems like the script is in fact hanging, since the pdf is only written after the timeout has been reached (and the script is thus terminated using a termsign 15.

The pdf looks correct though, and the exact same command runs perfectly on the CLI.

**Comment by osaris** [comment]
FYI, my problem was that some external links (CSS etc) weren't accessibles from the server that is running wkhtmltopdf (DNS misconfiguration). wkhtmltopdf is really slow to give up on missing ressources so the generation time was over 30 sec.

I fixed the problem by using realpath() to use local path for these ressources.

**Comment by barryvdh** [comment]
Again returning to this issue, I suddenly only get timeouts (existing project), but the files are generated.

Replacing the Symfony Process in the AbstractGenerator fixed it, so not sure why the Symfony Process is not responding..

```php
protected function executeCommand($command)
    {
        exec($command, $output, $status);

        return array($status, $output, $status == 0 ? '' : $output);
    }
```

**Comment by CharlyPoppins** [comment]
On our dedicated the timeout issue was solved by disabling ipv6.

**Comment by NiR-** [comment]
I close this issue because it is pretty old now and the only updates in the past year is about networking issues leading to timeouts. If you still face a similar problem please open a new issue.
