### ISSUE TITLE
'Symfony\Component\Process\Process' not found

### ISSUE THREAD

**Issue by scratcher28** [KnpLabs/snappy#171]
I am getting this error:

Fatal error: Class 'Symfony\Component\Process\Process' not found in snappy\src\Knp\Snappy\AbstractGenerator.php on line 467

PHP5.4 / Apache / WIndows 8.1-64bit

**Comment by jeremyb** [comment]
Hi @scratcher28

you probably have to run `composer update knplabs/knp-snappy` (or if it doesn't work `composer require symfony/process`) because I had a dependency to `symfony/process` on this PR #166.

**Comment by scratcher28** [comment]
It doesn't help.
I have all package files in vendor/symfony/process, but still get this error.

**Comment by jeremyb** [comment]
Are you using Snappy's `autoload` file or Composer's one?

**Comment by pilot** [comment]
@scratcher28 if class exist, but you still have error doens't found, that's mean that autoload not found the class or it not under the autoload

**Comment by jeremyb** [comment]
It's what I'm thinking too @pilot :) But I realized that the documentation indicates a custom autoloader file (https://github.com/KnpLabs/snappy/blob/master/src/autoload.php) and this one is not able to load `symfony/process` classes... I think we should advice to use the Composer's autoload file, no?

**Comment by scratcher28** [comment]
OMG, it was my mistake,
I had: require 'src/autoload.php', instead of require 'vendor/autoload.php
Really sorry!

**Comment by pilot** [comment]
@jeremyb yes make sense
