### ISSUE TITLE
The exit status code '1' says something went wrong: stderr: "wkhtmltopdf: cannot connect to X server "

### ISSUE THREAD

**Issue by asrivastavcog** [KnpLabs/snappy#172]
Hi,

I am getting this problem on ubuntu 12.02 system, server apache2 .
I have installed wkhtmltopdf --  0.12.1 installed on the server.
The exit status code '1' says something went wrong: stderr: "wkhtmltopdf: cannot connect to X server " stdout: "" command: /usr/bin/wkhtmltopdf --lowquality --margin-bottom '0' --orientation 'landscape' 

Any help would be appreciated.

Thanks,

**Comment by pilot** [comment]
wk is required X server to gerenerat pdf, if you haven't it you can use `xvfb`

**Comment by asrivastavcog** [comment]
I have already installed -- xvfb

**Comment by pilot** [comment]
http://stackoverflow.com/questions/9604625/wkhtmltopdf-cannot-connect-to-x-server?answertab=votes#tab-top
