### ISSUE TITLE
Looking to import a PDF as a template

### ISSUE THREAD

**Issue by devinfd** [KnpLabs/snappy#173]
I'm looking for a way to import a PDF as a template and then fill that PDF in with some text. Does anybody if this is possible with KnpLabs/snappy or where I might find some information on how to do this?

**Comment by akovalyov** [comment]
@devinfd well, it is impossible with wkhtmltopdf and Snappy lib. If you want to set PDF as a template, then this PDF should be edited, which is not so easy. You should either use https://github.com/Setasign/FPDI or https://github.com/cchantep/dhek to ease preparation of shapes and placeholders for content.
But I don't believe it's worth it. I'd rather build a good HTML template with help of any PHP templating engines. It will be much more maintainable and easy to use.
An then you can use Snappy :)

**Comment by devinfd** [comment]
Yea. Thats exactly what I was thinking/worried about.

**Comment by akovalyov** [comment]
@devinfd can I close it?

**Comment by devinfd** [comment]
Sorry about that
