### ISSUE TITLE
'Zoom' option not working?

### ISSUE THREAD

**Issue by prullenbak** [KnpLabs/snappy#174]
When I generate a pdf that contains fixed sizes, it looks like it's a factor 1.33 too small. After a lot of googling, this seems to be caused by a difference in dpi. wkhtml uses a dpi of 96, and css/html a dpi of 72. I don't know if that's true, but 96/72 = 1.33 so it seems logical. 

I thought I could solve this by setting the zoom option to 1.33, but it isn't working? Whatever I set the zoom option to, it just won't zoom. 

Can anyone help?

**Comment by prullenbak** [comment]
Nevermind...Turns out I had an older version (0.12.0) of wkhtmltopdf running...updated to 0.12.1, and now it seems to work!

**Comment by akovalyov** [comment]
@prullenbak just FYI, there is already https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.2 and https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.2.1 which have lots of bugfixes inside.
