### ISSUE TITLE
Remove --lowquality

### ISSUE THREAD

**Issue by shaneparsons** [KnpLabs/snappy#190]
By default it seems `--lowquality` is enabled and there doesn't seem to be an option to disable it.

I feel this should really be an option for the user to decide and not be enabled by default.

**Comment by akovalyov** [comment]
@shaneparsons indeed it is enabled by default. You can disable it via 
```php
$snappy->setOption('lowquality', null);
// or
$snappy->setOption('lowquality', false);
```
As for should it be enabled/disabled by default - this option with value exists since Snappy beginning. I'm afraid that if we disable it now, it will cause a lot of negative impact on lib users experience.
