### ISSUE TITLE
Images are not rendered if image is PHP file

### ISSUE THREAD

**Issue by JHGitty** [KnpLabs/snappy#191]
I use this sucessfully:
```php
<img src="<?= __DIR__.'/bla.png'; ?>" alt="" height="200">
```

It works fine and is rendered in the PDF file.

But this does not work:
```php
<img src="<?= __DIR__.'/barcode.php?text=bla'; ?>" alt="" height="200">
```

Any idea why it does not work?

I run the PHP script from CLI.

If I run barcode.php?text=bla over the webbrowser it works fine.

I have already checked the path, it is correct and not the issue.

**Comment by JHGitty** [comment]
Barcode.php https://github.com/davidscotttufts/php-barcode/blob/master/barcode.php

**Comment by akovalyov** [comment]
@JHGitty Unfortunately nothing we can do here, please check https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1855. The only thing you can do now is to cache your barcodes as images in filesystem and then use it..

**Comment by JHGitty** [comment]
@akovalyov Thanks for your help. In the meanwhile I've done the same as you explained as workaround.

**Comment by akovalyov** [comment]
You are welcome and sorry I came to you too late. Don't hesitate to ping us if you encounter an issue.
