### ISSUE TITLE
Fatal error: Class 'Symfony\Component\Process\Process' not found

### ISSUE THREAD

**Issue by praisedpk** [KnpLabs/snappy#197]
Fatal error: Class 'Symfony\Component\Process\Process' not found in \path\to\AbstractGenerator.php on line 478

On windows 7.

I am not using Symfony, neither does this project state that it requires Symfony. What is the reason for this error? Can you please help me resolve this?

Thanks.

**Comment by akovalyov** [comment]
@praisedpk hey.
Yes, we don't use symfony framework however we depend on [symfony component `symfony/process`](https://github.com/KnpLabs/snappy/blob/master/composer.json#L20)
How have you installed the project? Which version do you use?

**Comment by praisedpk** [comment]
I am using latest version, and I have extracted the package to use it (not using a package manager).

After reading another issue of previous date, I have copied process class from symfony, and its working.

Thanks for your help and time.

**Comment by akovalyov** [comment]
@praisedpk you are welcome.
Please, note that installation  via composer is preferred way. I encourage you to check it :)
Happy usage.
