### ISSUE TITLE
Error during requiring the package

### ISSUE THREAD

**Issue by adominik42** [KnpLabs/snappy#199]
Hy, here is my output after composer require, do you have any idea what am I messing up?

composer require h4cc/wkhtmltopdf-i386 0.12.x
You are running composer with xdebug enabled. This has a major impact on runtime
 performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package nikic/php-parser == 1.1.0.0 could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by NiR-** [comment]
Sorry for the late answer. This error isn't related to snappy, but I guess you already figured it out yourself.
