### ISSUE TITLE
Javascript not fired when using generateFromHtml but working with getOutputFromHtml

### ISSUE THREAD

**Issue by webdevilopers** [KnpLabs/snappy#200]
Original issue: https://github.com/KnpLabs/KnpSnappyBundle/issues/125

I have a TWIG template that uses javascript to style a `div` container with CSS to look like an image.

Outputting the HTML code or downloading it as `image` works fine using `getOutputFromHtml`:

* https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/GeneratorInterface.php#L54
* https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php#L190-L204

```php
        $topViewImageHtml = $this->renderView('app/_topView_image.html.twig', array(
            'configuration' => $configuration
        ));

        return new Response(
            $this->get('knp_snappy.image')->getOutputFromHtml($topViewImageHtml),
            200,
            array(
                'Content-Type'          => 'image/jpg',
                'Content-Disposition'   => 'filename="image.jpg"'
            )
        );
```

But when switching to `generateFromHtml` in order to directly store the file the result is empty.

* https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/GeneratorInterface.php#L33
* https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php#L159-L171

```php
$this->get('knp_snappy.image')->generateFromHtml(
    $topViewImageHtml,
    '/var/www/app/var/uploads/' . $entity->getId() . '/top-view.jpg',
    array('enable-javascript' => true)
);
```

I added a simply Javascript to the original template:
```html
<div id ="top-view"></div>
Some visible text.

<script>
document.write('Additional text');
</script>
```

Again the browser output would work and show `Additional text` when testing.

The image on the filesystem is blank.

Any reason javascript is not fired? Is there a way to store a file when using `getOutputFromHtml`?

**Comment by webdevilopers** [comment]
After comparing the different methods it is clear that they are doing the same job.

It was a problem with the absolute path of the javascript loaded via `<script>`.
A function from that loaded javascript seemed to block the others.

No issue!

Symfony2 solution for using absolute paths in twig:
```twig
<script src="{{ asset('/bundles/sonatacore/vendor/jquery/dist/jquery.min.js', absolute=true) }}" type="text/javascript"></script>
```

**Comment by roy-at-binate** [comment]
What is the solution?
