### ISSUE TITLE
[Question] Snappy SetXY alternative ?

### ISSUE THREAD

**Issue by a-moses** [KnpLabs/snappy#208]
their is any alternative with Snappy to Fpdf SetXY ?

```php

 $pdf -> SetXY(56, 20);
 $pdf -> text('text'); 
 $pdf ->Output( 'test.pdf);


```

**Comment by akovalyov** [comment]
@a-moses snappy is a wrapper over `wkhtmltopdf`, which is headless browser. So, if it is doable with CSS - it is doable and only with CSS - `wkhtmldopdf` doesn't allow any low-level layers manipulation.
