### ISSUE TITLE
footer-left encoding/umlaut problems

### ISSUE THREAD

**Issue by moritzgloeckl** [KnpLabs/snappy#210]
Hi,

I'm trying to add a footer with an umlaut to my document:

`$snappy->setOption('footer-left','ÖSTERREICH');`

Unfortunately the `Ö` isn't there... I've tried various combinations of the following:

`$snappy->setOption('footer-left',utf8_encode('ÖSTERREICH'));`
`$snappy->setOption('footer-left',utf8_decode('ÖSTERREICH'));`

Even trying to add the `Ö` via the correspondig utf8 escaped character. It works fine on Windows but not on my Linux server `Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64`. The php file containing the code is encoded in utf8, I've added the encoding option to snappy, the header charset (utf8) and even the meta charset in the html files. I'm really out of ideas!

Thanks!

**Comment by pelletiermaxime** [comment]
Also ran into this, with footer-center in my case. My workaround for now is:
```php
$snappy->setOption('footer-html', utf8_decode('ÖSTERREICH'))
```

**Comment by zzal** [comment]
Yeah, but how do you paginate with `--footer-html` option?

**Comment by zzal** [comment]
Well, it looks like it's in the docs:

```Footers And Headers:
  Headers and footers can be added to the document by the --header-* and
  --footer* arguments respectfully.  In header and footer text string supplied
  to e.g. --header-left, the following variables will be substituted.

   * [page]       Replaced by the number of the pages currently being printed
   * [frompage]   Replaced by the number of the first page to be printed
   * [topage]     Replaced by the number of the last page to be printed
   * [webpage]    Replaced by the URL of the page being printed
   * [section]    Replaced by the name of the current section
   * [subsection] Replaced by the name of the current subsection
   * [date]       Replaced by the current date in system local format
   * [isodate]    Replaced by the current date in ISO 8601 extended format
   * [time]       Replaced by the current time in system local format
   * [title]      Replaced by the title of the of the current page object
   * [doctitle]   Replaced by the title of the output document
   * [sitepage]   Replaced by the number of the page in the current site being converted
   * [sitepages]  Replaced by the number of pages in the current site being converted
  
  
  As an example specifying --header-right "Page [page] of [toPage]", will result
  in the text "Page x of y" where x is the number of the current page and y is
  the number of the last page, to appear in the upper left corner in the
  document.

  Headers and footers can also be supplied with HTML documents. As an example
  one could specify --header-html header.html, and use the following content in
  header.html:

  <html><head><script>
  function subst() {
      var vars = {};
      var query_strings_from_url = document.location.search.substring(1).split('&');
      for (var query_string in query_strings_from_url) {
          if (query_strings_from_url.hasOwnProperty(query_string)) {
              var temp_var = query_strings_from_url[query_string].split('=', 2);
              vars[temp_var[0]] = decodeURI(temp_var[1]);
          }
      }
      var css_selector_classes = ['page', 'frompage', 'topage', 'webpage', 'section', 'subsection', 'date', 'isodate', 'time', 'title', 'doctitle', 'sitepage', 'sitepages'];
      for (var css_class in css_selector_classes) {
          if (css_selector_classes.hasOwnProperty(css_class)) {
              var element = document.getElementsByClassName(css_selector_classes[css_class]);
              for (var j = 0; j < element.length; ++j) {
                  element[j].textContent = vars[css_selector_classes[css_class]];
              }
          }
      }
  }
  </script></head><body style="border:0; margin: 0;" onload="subst()">
  <table style="border-bottom: 1px solid black; width: 100%">
    <tr>
      <td class="section"></td>
      <td style="text-align:right">
        Page <span class="page"></span> of <span class="topage"></span>
      </td>
    </tr>
  </table>
  </body></html>
```

**Comment by NiR-** [comment]
I know that's pretty old @moritzgloeckl, but do you remember if you tried to add some umlaut to your html document? I suspect your linux server miss(ed) some fonts.

**Comment by NiR-** [comment]
Also did you check your locale as suggested by [this pending PR](https://github.com/KnpLabs/snappy/pull/194/files)?

**Comment by NiR-** [comment]
Doing some further research I stumbled upon [this commit](https://github.com/symfony/process/commit/f2d1eda0b736880a8d64c03fb29f9567ad0a4376) from `symfony/process`. It looks like they have fixed disappearing non ASCII characters since v2.7.24/v2.8.18/v3.2.3.

Nevertheless, other reasons are still valid:
* Missing/uninitialized/bad locale
* Missing font(s)

P.S.: Sorry for the multiple posts in a short amount of time.

**Comment by nocive** [comment]
Currently facing the same issue.
Found out that the problem goes away if you somehow force ```LC_CTYPE``` to be set but neither ```/etc/environment``` nor ```/etc/default/locale``` seem to have any effect in the shell where ```wkhtmltopdf``` is invoked.

The workaround that is currently working for me is to add ```setlocale('LC_CTYPE=en_US.UTF-8');``` to the ```AbstractGenerator``` class but not that happy with it as a permanent solution.

**Comment by NiR-** [comment]
@nocive What does trigger the PDF generation in your case? A HTTP request or a CLI command manually run?

**Comment by nocive** [comment]
PHP CLI command

**Comment by nocive** [comment]
Sorted it out by:
- calling ```setlocale(LC_CTYPE, 'en_US.utf8');``` in CLI context, which takes care of ```escapeshellarg``` stripping out utf8 characters
- overriding the ```buildCommand``` method from the ```Pdf``` class and forcing ```LC_CTYPE``` to be set in the shell where ```wkhtmltopdf``` runs

```php
class Pdf extends \Knp\Snappy\Pdf
{
    /**
     * {@inheritdoc}
     */
    protected function buildCommand($binary, $input, $output, array $options = [])
    {
        return 'LC_CTYPE=en_US.utf8 ' . parent::buildCommand($binary, $input, $output, $options);
    }
}

**Comment by NiR-** [comment]
@nocive Wow, I'm not really sure how it could work in one case and not in another (especially since you're running it from a CLI command). I have to investigate this a bit more to understand what's going on. Thank you a lot for your precious input! If I don't see any rationale around this, I might give up and publish your snippet as a patch.

**Comment by nocive** [comment]
@NiR- No worries, glad it was useful.

It could be the case that this is also impacted by server environment, but I can't really confirm or deny. For our use case it makes sense to make the code resilient enough to cope with the fact that ```LC_CTYPE``` may or may not be set in the shell, specially since we found out that changes to ```/etc/default/locale``` and ```/etc/environment``` seemed to make no difference for our setup.

**Comment by zhangatjlu** [comment]
I try the suggestions above to output Chinese in header (v1.1.0 + wkhtmltopdf 0.12.5 on Ubuntu18.04), but failed. Has other recommendations？

**Comment by 233cy** [comment]
我也出现页脚页眉内容丢失的问题，在回答中找到了解决办法，但是官方为什么不解决这个问题？（使用：setlocale(LC_CTYPE, null);）
