### ISSUE TITLE
jQuery function issues w/o using a CDN

### ISSUE THREAD

**Issue by shaneparsons** [KnpLabs/snappy#213]
It's hard to demonstrate, but I've noticed some of my functions that rely on jQuery don't work properly unless I'm including jQuery from a CDN.

The CDN and local versions I'm using are the exact same (2.2.2), so I'm not sure why one works better than the other. Any one have any ideas?

I'm using a Laravel wrapper for Snappy by the way... I just figured this issue would be a better fit here.

**Comment by akovalyov** [comment]
it is hard to understand without any code examples, what is going on.
I assume that your js just doesn't have enough time to be executed in the small period between page was loaded in wkhtmltopdf and the moment when it was rendered as pdf.
You might try https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/Pdf.php#L138

**Comment by shaneparsons** [comment]
The 'javascript-delay' was actually one of the first things I tried with no success.

I'll try setting up an example when I get the chance.

**Comment by akovalyov** [comment]
OK, thank you for feedback.
http://stackoverflow.com/questions/23774697/wkhtmltopdf-and-the-jquery-ready-function might be also related.

**Comment by NiR-** [comment]
@shaneparsons Do you still face this issue, or could you close it?

**Comment by shaneparsons** [comment]
I haven't touched the project for quite some time now, so I'm not sure. I'll post back here if it pops up again in the future.
