### ISSUE TITLE
Using $snappy->getOutputFromHtml()

### ISSUE THREAD

**Issue by ogrosko** [KnpLabs/snappy#214]
Using $snappy->getOutputFromHtml() generated pdf is not possible to open in browser. Only in pdf viewer (acrobat reader, etc.)

I have to change method to $snappy->getOutput()

**Comment by akovalyov** [comment]
`generateFromHtml` saves pdf content to given file.
It doesn't return anything related to PDF content, so that's why browser built-in viewer couldn't handle it, I assume.
