### ISSUE TITLE
generateFromHtml() options: "footer-right" => "Page [page] of [toPage]"

### ISSUE THREAD

**Issue by pockie** [KnpLabs/snappy#216]
When I call:

``` php
$options = ["footer-right" => "Page [page] of [toPage]"];
$options["page-size"] = "A4";
$content = $this->fixLinks($content);
$filename = "test.pdf";
$this->snappy->generateFromHtml($content,  '/web/pdf/' . $filename, $options, true);
```

I get the following error:

```
The file '/web/pdf/test.pdf' was not created (command: /usr/local/bin/wkhtmltopdf --lowquality --page-size 'A4' --footer-right 'Page [page] of [toPage]' '/tmp/knp_snappy574318c420cd15.83439227.html' '/web/pdf/test.pdf')
```

If I use the console and call the command:

```
/usr/local/bin/wkhtmltopdf --lowquality --page-size 'A4' --footer-right "Page [page] of [toPage]" '/tmp/knp_snappy574318c420cd15.83439227.html' '/web/pdf/test.pdf' 
it works. 
```

The difference is that in console I use double quotes (") for encolsing Page [page] of [toPage]. The command created by snappy encloses Page [page] of [toPage] with single quotes (').

Do you know what I do wrong?

**Comment by NiR-** [comment]
Unfortunately I'm not able to reproduce your issue. Since this is pretty old, do you still need some help?

**Comment by pockie** [comment]
No. I don`t help anymore. You are right it pretty old. I think I solbed the problem somehow.

**Comment by NiR-** [comment]
Cool :)

**Comment by oscarmolinadev** [comment]
Ubuntu 16.04 same error in log this:

`QSslSocket: cannot resolve SSLv3_client_method`
