### ISSUE TITLE
set a background image

### ISSUE THREAD

**Issue by aymenpeak** [KnpLabs/snappy#217]
there is setOption('no-background',false) but i could'nt find a way to put the background image's url ...
if i did it in html does not fit the hole page

**Comment by MitchellBouwman** [comment]
Maybe add` "background-size: cover;"` to it? :) It wil stretch to full screen in the correct ratio.

**Comment by NiR-** [comment]
@MitchellBouwman's answer seems legit. I close this issue because of inactivity
