### ISSUE TITLE
Setup on linux server by control panel

### ISSUE THREAD

**Issue by voltan** [KnpLabs/snappy#219]
Hello

I development php application by zend framework 2 and use snappy to generate image, on localhost ( fedora linux 23 ) it work without problem. 

But I want use my application on centos server by cpanel or directadmin control panel, and I see snappy use php process class , how I can install process class on my server whit cpanel easyapache or directadmin custombuild ? any disable function needed to open? and shell access needed ?

Or I need setup and load Symfony Process on server side ?
- On localhost I don't use Symfony and install php-process by yum ( dnf )
- On server I install wkhtmltopdf by this doc : https://jaimegris.wordpress.com/2015/03/03/how-to-install-wkhtmltopdf-in-centos-6-5/

**Comment by NiR-** [comment]
We use `symfony/process` for executing wkhtmltopdf. It is declared as a dependency of snappy so you don't need to install it yourself (composer will do that for you). `symfony/process` uses `proc_open` function, but this is not related to process extension. Thus you only need a working php and no extra extensions to run Snappy.
