### ISSUE TITLE
How to get sterr output after command execution?

### ISSUE THREAD

**Issue by gam6itko** [KnpLabs/snappy#223]
I need to log it

**Comment by NiR-** [comment]
Hey @gam6itko, 

First of all, thank you for your interest for snappy and sorry for the long awaited answer. Currently there's no way in the library to do it. So merely you need to overload the current generator or just add some dump calls where you want.

I created a little issue some time ago about backporting the LoggableGenerator from snappy-bundle to this lib (see #258). As soon as I've got some time to do it, I will. Or I'd be glad to merge any PR doing it :)

**Comment by NiR-** [comment]
I added logging capabilities in order to ease debugging of snappy/wkhtmltopdf. You can now call `setLogger` on the generators to enable logging. By default generators use a NullLogger. See #264.
