### ISSUE TITLE
Error: Failed loading page https://www.google.co.in

### ISSUE THREAD

**Issue by andyideologi** [KnpLabs/snappy#225]
Fatal error: Uncaught RuntimeException: The exit status code '1' says something went wrong: stderr: "Loading pages (1/6) [> ] 0% [======> ] 10% [============================================================] 100% Error: Failed loading page https://www.google.co.in (sometimes it will work just to ignore this error with --load-error-handling ignore) " stdout: "" command: vendor/h4cc/wkhtmltopdf --lowquality 'https://www.google.co.in' '/var/folders/38/_2dxqbwx61b361td_1n4ffrh0000gp/T/knp_snappy57aee113c4ea83.11210544.pdf'. in /Applications/MAMP/htdocs/test/snappy/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:336 Stack trace: #0 /Applications/MAMP/htdocs/test/snappy/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(151): Knp\Snappy\AbstractGenerator->checkProcessStatus(1, '', 'Loading pages (...', 'vendor/h4cc/wkh...') #1 /Applications/MAMP/htdocs/test/snappy/vendor/knplabs/knp-snappy/src/ in /Applications/MAMP/htdocs/test/snappy/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php on line 336

**Comment by daudmalik06** [comment]
@andyideologi  i had same issue with wkhtmltopdf for this purpose born new library which uses chrome headless as a back-end so no more these kind of problems try this 
https://github.com/daudmalik06/PhpChromeToPdf

**Comment by andyideologi** [comment]
Thank you so much @daudmalik06  Great Work!!!
