### ISSUE TITLE
code 1 due to network error: ContentOperationNotPermittedError

### ISSUE THREAD

**Issue by nam-co** [KnpLabs/snappy#227]
Hi, appreciate any help anyone can give me, Im trying to create the pdf, the process goes well, but it seems the /tmp/ path is wrong and I don't know how to change it, please help

Done 
Exit with code 1 due to network error: ContentOperationNotPermittedError
"
stdout: ""
command: /home/71754-55579.cloudwaysapps.com/gvtnjrtyeb/public_html/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy57cdd005371ac1.47960877.html' '/tmp/knp_snappy57cdd005372238.84465033.pdf'.

**Comment by nam-co** [comment]
sometimes I also get ContentNotFoundError

**Comment by aguidis** [comment]
Hello,
Can you share the content of the html please ?
This error can occur when there are links to external resources

**Comment by nam-co** [comment]
Hi Adrien thanks for your response, I appreciate it a lot, here are the 2 links

This is the error response:
https://propi.co/api/download_item_pdf?username=inmuebles-sas&type=project_id&id=1

This is  how the page looks like:
https://propi.co/inmuebles-sas/proyecto/om-club-house

Appreciate any help

regards

**Comment by akovalyov** [comment]
On your page ` https://propi.co/inmuebles-sas/proyecto/om-club-house` you have a resource with 403 http code. Most likely it is the cause. 
You can use `--load-error-handling` with `ignore` handler or `--load-media-error-handling` with `ignore` handler. If it doesn't help, you can check out http://wkhtmltopdf.org/usage/wkhtmltopdf.txt for more options. 
Anyway, it is wkhtmltopdf which fails, not the lib, so I am about to close that as it is not related. Please, let me know the results.

**Comment by nam-co** [comment]
Hi Adrien thanks for your response, I appreciate it a lot, here are the 2 links

This is the error response:
https://propi.co/api/download_item_pdf?username=inmuebles-sas&type=project_id&id=1

This is  how the page looks like:
https://propi.co/inmuebles-sas/proyecto/om-club-house

Appreciate any help

regards

**Comment by akovalyov** [comment]
something with notifications went wrong ^^

**Comment by nam-co** [comment]
yes I see, Adrian I know is not your package error, but maybe you have an idea, I fix the 403 and now I get a ContentNotFoundError error, could it be the /tmp/ path is not writable? how can I change this path? appreciate any help

**Comment by akovalyov** [comment]
usually with this error pdf is still generated, so you can check the pdf file. 
As fot `ContentNotFoundError` itself, I encourage you to check out https://github.com/wkhtmltopdf/wkhtmltopdf/search?utf8=%E2%9C%93&q=ContentNotFoundError&type=Issues. You might find an answer there.
