### ISSUE TITLE
Does it support CSS3/Flexboxes?

### ISSUE THREAD

**Issue by jex310** [KnpLabs/snappy#229]

**Comment by akovalyov** [comment]
wkhtmltopdf 0.12 is based on QT 4.8, which has old Webkit engine, so flexbox is not fully supported there. As stated in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522#issuecomment-34928787 and in https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1522#issuecomment-159767618, you can use flexbox with -webkit prefixes. You can check out compatibility at http://caniuse.com/#compare=chrome+13.

**Comment by eni23** [comment]
in arch linux the wkhtmltopdf package is linked to qt5 and there flexbox is supported flawlessly
