### ISSUE TITLE
installation issue in symfony 3.15 

### ISSUE THREAD

**Issue by dulajsan** [KnpLabs/snappy#234]
installation failed for Symfony version 3.15

![image](https://cloud.githubusercontent.com/assets/12482873/22010855/bb6f0ea0-dcb1-11e6-934f-2bb0632bc659.png)

**Comment by NiR-** [comment]
I'm not sure this is related to snappy: there's nothing indicating it. Could you run `composer why symfony/property-access` and paste the result here please?

**Comment by NiR-** [comment]
No answer in the last 3 months and this is not related to snappy, thus I close this issue.
