### ISSUE TITLE
Generating multiple PDF files for download.

### ISSUE THREAD

**Issue by agrandin** [KnpLabs/snappy#238]
If I want to generate multiple PDF-files for download, is it possible? 
Or should I save all generated PDF-files to server (is it possible) and then create a zip-archive of all the PDF files and let the user download that file?

**Comment by NiR-** [comment]
No, unfortunately it's not possible to send multiple files in one http response. As stated by [this stackoverflow answer](https://stackoverflow.com/questions/2339440/download-multiple-files-with-a-single-action?answertab=votes#tab-top):

> There are two solutions:
Open x amount of windows to initiate the file downloads (this would be done with JavaScript)
preferred solution create a script to zip the files
