### ISSUE TITLE
Resetting options

### ISSUE THREAD

**Issue by cdarken** [KnpLabs/snappy#241]
Is there any way to reset all or some options to defaults? For instance if you generate more than one PDF in one call.

**Comment by NiR-** [comment]
Nope, not currently. You need to rely on something like that:
```php
$options = $generator->getOptions();
$generator->setOptions(array_combine(array_keys($options), array_fill(0, count($options), null));
```

**Comment by alexpozzi** [comment]
https://github.com/KnpLabs/snappy/pull/375

**Comment by alexpozzi** [comment]
Closing as [this](https://github.com/KnpLabs/snappy/pull/385) PR has been merged.
