### ISSUE TITLE
autoload.php not found inside latest release package

### ISSUE THREAD

**Issue by webnius-infotech-dwx** [KnpLabs/snappy#252]
Please help. i am trying to use snappy but autoload.php is not found inside latest release. it is removed ...? else what to use instead..?

**Comment by NiR-** [comment]
AFAIK there has never been any autoload.php provided with snappy. Are you talking about the `autoload.php` that composer creates? Could you provide more details about what you're trying to do please?

**Comment by Speedz007** [comment]
I believe he is referring to the first line in the php usage code. The documentation isn't exactly noob friendly.

`require __DIR__ . '/vendor/autoload.php';`

**Comment by webnius-infotech-dwx** [comment]
thanks
