### ISSUE TITLE
Having issue generating PDF of reactjs app

### ISSUE THREAD

**Issue by needcaffeine** [KnpLabs/snappy#253]
I had this whole thing working, but needed to convert this page over to ReactJS, and now the PDFs are all blank. I tried adding the polyfills but that didn't seem to help. Any obvious things I'm missing?

**Comment by NiR-** [comment]
Hello :)

Have you disabled `disable-javascript`  option? Could you dump the command executed here please ([see here](https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#frequently-asked-questions))?

**Comment by needcaffeine** [comment]
Sorry this took me a while, but here it is: `/site/app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --debug-javascript --enable-javascript 'http://localhost.docker/certificate/6bd?format=html' 'test.pdf''`

**Comment by NiR-** [comment]
Have you try `--javascript-debug` option?

> --javascript-delay <msec>       Wait some milliseconds for javascript finish (default 200)

You should also consider searching on the wkhtml repo and on their mailing list. There might be some answers to your issue.

**Comment by NiR-** [comment]
Any news @needcaffeine?
