### ISSUE TITLE
ContentNotFoundError while trying to save $pdf->output() to AWS

### ISSUE THREAD

**Issue by pcartagena74** [KnpLabs/snappy#254]
Here's what I would like to do (in my Laravel implementation): 
- render a view into a PDF 
- save that PDF into an AWS S3 bucket

Having read through the other posts, I've changed all of the URLs so that they are not relative and I have verified that the following code does, indeed, create a pdf.  

When saved, it is writing to a default location which I want to change.

         $pdf = PDF::loadView('v1.public_pages.event_receipt', $x)
        ->setOption('disable-javascript', false)
        ->save('receipt.pdf');

**Aside:** I've noticed when opening the saved PDF, I must do so via File->Open (find the file).  It looks fine when I open it that way.  When double clicking, an error eventually triggers saying, "Cannot connect to DDE server."

I've tried to experiment with saving the pdf content to my aws bucket by doing:

      Flysystem::connection('s3_receipts')->put($receipt_filename, $pdf->output(), ['visibility' => AdapterInterface::VISIBILITY_PUBLIC]);

I get the following stderr text out when attempting the above:

     The exit status code '1' says something went wrong:
     stderr: "Loading pages (1/6)
     [> ] 0%
     [======> ] 10%
     [========> ] 14%
     Warning: SSL error ignored 
     Warning: SSL error ignored
     Warning: SSL error ignored
     Warning: SSL error ignored
     [==========> ] 18%
     [================> ] 27%
     [===================> ] 32%
     [=====================> ] 36%
     [=========================> ] 42%
     [==========================> ] 44%
     [============================> ] 48%
     [===============================> ] 52%
     [====================================> ] 60%
     [=======================================> ] 65%
     Warning: SSL error ignored 
     Warning: SSL error ignored
     [==========================================> ] 71%
     [============================================> ] 74%
     [==============================================> ] 77%
     [================================================> ] 80%
     [==================================================> ] 84%
     [====================================================> ] 88%
     [============================================================] 100%
     Counting pages (2/6) 
     [============================================================] Object           1 of 1
     Resolving links (4/6) 
     [============================================================] Object      1 of 1
     Loading headers and footers (5/6) 
     Printing pages (6/6)
     [> ] Preparing
     [============================================================] Page      1 of 1
     Done 
     Exit with code 1 due to network error: ContentNotFoundError
     "
     stdout: ""

I have verified that I can write to the AWS location I'm attempting to use.

Please help.

**Comment by NiR-** [comment]
Looks like the pdf generation fails even before the upload. Could you try to dump the wkhtmltopdf command and post it here please ([see here](https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#frequently-asked-questions))? Also, try to execute the command in a terminal.

**Comment by pcartagena74** [comment]
Apologies.  I had missed a broken javascript link in the html.  Everything works.  This package is amazing.
