### ISSUE TITLE
Snappy generating 404 pages

### ISSUE THREAD

**Issue by apsg** [KnpLabs/snappy#257]
I'm having strange issue while generating PDF's with snappy. 

If I run wkhtmltopdf directly:

```
$command = 'xvfb-run --server-args="-screen 0, 1024x768x24" -a wkhtmltopdf http://atlaswork.net/preview.php?id=7258&wkhtmltopdf=1&userid=10 pdf.pdf';

exec( $command );
```

The output is correct. 

But if I try to run the same url through snappy I get a PDF containing 404 page:

```
require __DIR__ . '/vendor/autoload.php';

use Knp\Snappy\Pdf;
$snappy = new Pdf('xvfb-run --server-args="-screen 0, 1024x768x24" -a wkhtmltopdf');
  
$snappy->setOption('margin-bottom', 0 );
$snappy->setOption('margin-top', 0 );
$snappy->setOption('margin-left', 0 );
$snappy->setOption('margin-right', 0 );


header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="form123.pdf"');

echo $snappy->getOutput( "http://atlaswork.net/preview.php?id=7258&wkhtmltopdf=1&userid=10" );
exit();
```

What can be wrong? How can I diagnose why snappy is returning 404s?

**Comment by NiR-** [comment]
@apsg Your reproducer is working well on my computer (php cli) :| What OS do you use? Also, are you running it through cli or http? You can try to add some debug statements in the `executeCommand` method to dump stdout and stderr.

**Comment by apsg** [comment]
It is debian based hosting. 

Also I found that in server logs there are strange urls:

`88.99.205.66 - - [24/Jul/2017:17:13:42 +0200] "GET /preview.php%5C?id=7258%5C&wkhtmltopdf=1%5C&userid=10 HTTP/1.1" 404 1148 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) wkhtmltopdf Safari/538.1" "www.atlaswork.net" `

It looks like if snappy was trying to escape some characters in a weird manner.

**Comment by NiR-** [comment]
Which version of snappy do you use?

**Comment by apsg** [comment]
Latest. Just updated it via composer.

**Comment by NiR-** [comment]
Could you dump the command [right before it got executed by symfony/process](https://github.com/symfony/process/blob/master/Process.php#L306) please? Did you try to run the same script from cli to see if the error happen too?

**Comment by NiR-** [comment]
Could you provide feedback before the end of the week please? If you don't, I'm gonna close this issue.

**Comment by apsg** [comment]
Sry, we haven't solved the issue, switched to other system. You can close this issue, but it isn't solved.

**Comment by NiR-** [comment]
Too bad! :(
