### ISSUE TITLE
Possible to remove margins only on cover page?

### ISSUE THREAD

**Issue by zakiaziz** [KnpLabs/snappy#259]
Hi, I'm making a call like this within laravel: 
```php
PDF::loadView('reports.body', ['data' => $data])
->setOrientation('landscape')
->setOption('cover', view('reports.cover', ['coverData' => $coverData]))
->setOption('header-html', view('reports.header', ['headerData' => $headerData]))
->setOption('footer-html', view('reports.footer', ['footerData' => $footerData]))
->setOption('margin-bottom', '0mm')
->setOption('margin-top', '0mm')
->setOption('margin-right', '0mm')
->setOption('margin-left', '0mm');
```
But the problem with that is it removes the header and footer in the body.

Is there an option to remove the margins only on the cover page?

**Comment by tushar32** [comment]
Same problem for me as well.Is this a bug in laravel snappy?

**Comment by zakiaziz** [comment]
Probably not (though I'm not 100% sure). Laravel Snappy should be just a wrapper around this library.

**Comment by tushar32** [comment]
What is the solution then? I am thinking of using pdfmerger.

**Comment by tushar32** [comment]
How did you create Table of content using snappy?

**Comment by tushar32** [comment]
http://ec2-35-177-220-250.eu-west-2.compute.amazonaws.com/shopeassy/setup/

**Comment by zakiaziz** [comment]
If the organizers are still present: I'm still looking for help on this issue

**Comment by NiR-** [comment]
@zakiaziz I'm afraid there's no solution for your problem: AFAIK margin applies on every pages of the document. As suggested by @tushar32, you can try to generate multiple PDFs and merge them together.

**Comment by tushar32** [comment]
In this case there is one more bug, if I merge two or more files together the table of content doesn't work.

**Comment by guicara** [comment]
Hello,

Someone have created a PR request on the wkhtmltopdf repository for this feature.

Please see the ongoing issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3635
