### ISSUE TITLE
why this err?

### ISSUE THREAD

**Issue by chhaunkar96** [KnpLabs/snappy#260]
Fatal error: Uncaught exception 'RuntimeException' with message 'The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified. " stdout: "" command: /vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality "http://realtycloudsystems.com/Agent-test/Admin/completeTmp.php?token=22" "C:\Users\RCS\AppData\Local\Temp\knp_snappy597ee578a9c758.29184621.pdf".' in C:\xampp\htdocs\snappy\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php:336 Stack trace: #0 C:\xampp\htdocs\snappy\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php(151): Knp\Snappy\AbstractGenerator->checkProcessStatus(1, '', 'The system cann...', '/vendor/h4cc/wk...') #1 C:\xampp\htdocs\snappy\vendor\knplabs\knp-snappy\src\Knp\Snappy\Pdf.php(62): Knp\Snappy\AbstractGenerator->generate('http://realtycl...', 'C:\\Users\\RCS\\Ap...', Array, false) #2 C:\xampp\htdocs\snappy\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php(180): Knp\Snappy\Pdf->generate('http://realtycl...', 'C:\\Use in C:\xampp\htdocs\snappy\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php on line 336

**Comment by NiR-** [comment]
The path of your binary is wrong: `/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64`. I believe you don't have any `vendor` folder at the root of your filesystem, but rather you're trying to call the wkhtmltopdf from vendor/bin directory, relative to the root of your project. Thus, you should remove the leading slash.

**Comment by chhaunkar96** [comment]
I installed this by composer. 
![snappy](https://user-images.githubusercontent.com/29665934/28769221-3ea6e164-75f8-11e7-903f-7831bf4b44f1.PNG)

**Comment by NiR-** [comment]
I guess you didn't install `snappy` at the root of your filesystem, but rather in `C:\Users\RCS\Ap...`. Thus, you should use something like: `__DIR__ . '/vendor/bin/wkhtmltopdf-amd64`.

* Can you post a code snippet showing your problem please? Would be easier to understand what's wrong.
* Are you sure to use the right binary? Your screenshot looks like Windows explorer, but you install binaries for linux.

**Comment by chhaunkar96** [comment]
1-I am not sure about binary.

**Comment by chhaunkar96** [comment]
Sorry for English mistake.
1-I'm not sure binary.
2-I'm using windows 7(64bit) and 32bit xampp
3-I'm using snappy first time.

**Comment by NiR-** [comment]
Ok, so look at wkhtml download page and try with either MSVC or MinGW bin: https://www.wkhtmltopdf.org/downloads.html.

If it doesn't work, please add a code snippet so I could more easily understand what you do.

**Comment by chhaunkar96** [comment]
Thanks . 
Its done.
<?php
require 'vendor/autoload.php';
use Knp\Snappy\Pdf;
$snappy = new Pdf(__DIR__.'\vendor\h4cc\wkhtmltopdf\bin\wkhtmltopdf32');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
echo $snappy->getOutput('http://realtycloudsystems.com/Agent-test/Admin/completeTmp.php?token=22');
?>

and binary download from https://github.com/wemersonjanuario/wkhtmltopdf-windows


            Thnks again.... :-)

**Comment by chhaunkar96** [comment]
I have a problem again :
echo $snappy->getOutput('http://www.github.com'); this function working fine but $snappy->generateFromHtml('<h1>Bill</h1><p>You owe me money, dude.</p>','test.pdf'); this not working.

**Comment by NiR-** [comment]
So.. No more problem? :) Can I close it? :)

**Comment by chhaunkar96** [comment]
Wait don't close now. I'll use it now on my dedicated server cent os 7.

**Comment by NiR-** [comment]
Could you add executable perm to the binary? (on your server: `chmod +x vendor/h4cc/wkhtmltopdf-amd64-centos7/bin/wkhtmltopdf-amd64`)

**Comment by chhaunkar96** [comment]
Thanks
It's done.
You can close it .:)
