### ISSUE TITLE
After updated the last version, I got this exception. 

### ISSUE THREAD

**Issue by semsphy** [KnpLabs/snappy#274]
Hello,

```
ErrorException: var_export does not handle circular references 
vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:117
```
Thanks

**Comment by NiR-** [comment]
Hello @semsphy, could you provide a snippet to reproduce this bug please? I'd like to see how it could happen because it's totally unexpected.

**Comment by barryvdh** [comment]
What kind of options are you setting?

**Comment by semsphy** [comment]
There are my options. @NiR- I'm sorry I didn't testing yet, I will try to reproduce and report you ASAP.

```php
<?php
return \SnappyPDF::loadHTML($view)
        ->setPaper($paper);
        ->setOption('header-html', $header);
        ->setOption('footer-html', $footer);
        ->setOption('margin-top', $top);
        ->setOption('margin-bottom', $bottom);
        ->setOption('margin-right', $right);
        ->setOption('margin-left', $left);
        ->stream($title.'.pdf');
```

**Comment by barryvdh** [comment]
Are they all strings? Eg. the html settings need to be URL's (not objects that can be cast to string)

**Comment by semsphy** [comment]
`view('package::partial.'.$header, $data)`, it is object.

**Comment by barryvdh** [comment]
Yeah, don't to that. Create a route or html file and pass the URL/path as option.

**Comment by barryvdh** [comment]
See https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

> --footer-html <url>             Adds a html footer

(Although in my opinion, it would be very neat if Snappy would convert the HTML to a  HTML file on disk to make it easier to use footers/headers to be generated with HTML)

**Comment by semsphy** [comment]
@barryvdh, I'm using your `laravel-snappy`, and I use `view()` to pass data to `header.blade.php`.
And it works fine in snappy v0.5.0.

**Comment by NiR-** [comment]
@semsphy I don't know about laravel but I guess `view()` returns an object which has some cyclic dependency on the generator. I also make the assumption that this object has a `__toString()` method returning the rendered view. Contrary to what @barryvdh said, you can pass html content to `header-html` and `footer-html` options, and Snappy will write them in a temporary file and it will feed wkhtmltopdf with that.

So yeah, sorry, it looks like we introduced a minor BC break we weren't aware of, in the v1.0.0. I'm going to document it. But first, could you confirm that casting the result of `view()` works correctly in your case?

**Comment by barryvdh** [comment]
Ah sorry, did not know that.  I would swear I've tried that before and didn't work. But cool :)

That does indeed explain why it worked before. Can't we check if it's an object? Eg.

```php
 $this->logger->debug(sprintf('Set option "%s" to "%s".', $name, (is_object($value) ? get_class($value) : var_export($value, true))));
```

Or use the context of the logger, which might be more reliable?

```php
 $this->logger->debug(sprintf('Set option "%s"', $name), ['value'=> $value]));
```


@semsphy I can probably override the setOption() call to render `Renderable` classes to string.

**Comment by NiR-** [comment]
> Ah sorry, did not know that. I would swear I've tried that before and didn't work. But cool :)

No problem :)

> Or use the context of the logger, which might be more reliable?

Indeed, that would be better to use it rather than dumping the variable in the message. Do you want to submit a patch? :)

**Comment by NiR-** [comment]
@semsphy I just released a new patch version. Use it and your problem will disappear ;)
