### ISSUE TITLE
support different headers/footers on some pages

### ISSUE THREAD

**Issue by SimonHeimberg** [KnpLabs/snappy#288]
Different headers/footers seem to be supported by wkhtml2pdf now. 

According to one [faq](https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#q-is-it-possible-to-include-an-header-andor-footer-only-on-some-specific-pages), wkhtml2pdf can not generate different headers. But according to https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2482 this is possible (since version?).
But this requires to mix options and arguments:
`wkhtml2pdf --general-option --another-general-option content_1.html --header-html header_for_1.html content_2_with_no_header.html content_2.html --header-html header_for_3.html`
How can I do this with snappy?

**Comment by seyfcom** [comment]
I would love to get a solution ! Please tell me it is possible !
