### ISSUE TITLE
open pdf problem

### ISSUE THREAD

**Issue by CmderQ** [KnpLabs/snappy#289]
hi，I use that and a pdf file came into being. When I opened it by pdf-xchange software， it alert  “Error[PDF Structure 40]:Invalid file format”. I want to why it generator?

**Comment by NiR-** [comment]
Hello,

Have you tried to open it with another software? Nonetheless, this is not related to snappy itself but to wkhtmltopdf (the underlying PDF generator).

To better understand what's going on, you should run wkhtmltopdf by hand until you have an acceptable result (see the two first questions in [our FAQ]( https://github.com/KnpLabs/snappy/blob/master/doc/faq.md#q-it-does-not-work-and-everything-is-broken)). If you can't find what's going wrong, you can either check the technique describe in the last question/answer of the FAQ and/or ask for help on SO or [wkhtmltopdf repo](https://github.com/wkhtmltopdf/wkhtmltopdf).

**Comment by CmderQ** [comment]
Ok，Thank you very much. I will try it!
