### ISSUE TITLE
multiple input files

### ISSUE THREAD

**Issue by klausbiedermann** [KnpLabs/snappy#29]
I installed and tested snappy library for pdf generating.
Everything works fine.
But is there a way to have multiple html url´s or html files as input.

When i try this:
$snappy->generate('http://bag2go.de http://bag2go.de/taschen.php http://bag2go.de/material.php', 'tmp/test-5.pdf');

i get this:
Error: Failed loading page http://bag2go.de/taschen.php http://bag2go.de/material.php

When i try the same on console bash it works:

wkhtmltopdf-i386 http://bag2go.de http://bag2go.de/taschen.php http://bag2go.de/material.php /var/www/upload/test.pdf

Any hints?

best regards

Klaus

**Comment by silasrm** [comment]
This function are broken! @kusmierz

**Comment by akovalyov** [comment]
https://gist.github.com/akovalyov/a0e833b1ffcadf48b3d3 here is a small working gist which demonstrates that generating PDF from multiple URLs works. However I agree that Snappy API is a little bit messy and it would be better to refactor it, but it is another issue not related to this one.

**Comment by silasrm** [comment]
In my test, the PDF contain 1 url content, the rest is loosed.

```
<?php

require_once 'vendor/autoload.php';

use Knp\Snappy\Pdf;

$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');

file_put_contents('teste.pdf', $snappy->getOutput(
    array(
        'http://www.schoolofnet.com/2015/07/trabalhando-com-repository-no-laravel/',
        'http://www.schoolofnet.com/2015/04/como-usar-os-metodos-magicos-no-php/',
        'http://www.schoolofnet.com/2015/04/enviando-emails-utilizando-swift-mailer/',
        'http://www.schoolofnet.com/2015/04/instalando-e-integrando-apache-com-php-no-windows/',
    )
));
```

Versions:
"knplabs/knp-snappy": "^0.4.0"
wkhtmltopdf 0.12.2 (with patched qt)

**Comment by silasrm** [comment]
@akovalyov your code is ok here. But mine is wrong.
