### ISSUE TITLE
Why the image is not clear generate by wkhtmltoimage

### ISSUE THREAD

**Issue by gaoyl101** [KnpLabs/snappy#293]
Successfully,I use wkhtmltoimage to generate an image . but the image is not too clear. And how to make it clear?

**Comment by NiR-** [comment]
@gaoyl101 Could you describe your env? Do you use wkhtmltoimage on Windows, Linux (what distro?) or macOS? Blurry images can be caused by different factors, depending of your OS. But you can first try to increase image DPI to >= 300 (`--dpi 300`).

**Comment by bananakiu** [comment]
change the --zoom to 4! it seems to fix the issue (i can't explain why)

But, i saw it on this link: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1926
