### ISSUE TITLE
Parse error in process.php

### ISSUE THREAD

**Issue by Jokrion** [KnpLabs/snappy#294]
Hello, as said in the title, i get a parse error in process.php on line 273 when i try to generate a pdf. Did i make a mistake while installing snappy?

Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /vendor/symfony/process/Process.php on line 273

**Comment by NiR-** [comment]
Could you provide the output of `composer show symfony/process` please? Did you look at line 273?

**Comment by Jokrion** [comment]
The result from composer show symfony/process : 
name     : symfony/process
descrip. : Symfony Process Component
keywords :
versions : * v3.4.3
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/symfony/process.git ff69f110c6b33fd33cd2089ba97d6112f44ef0ba
dist     : [zip] https://api.github.com/repos/symfony/process/zipball/ff69f110c6b33fd33cd2089ba97d6112f44ef0ba ff69f110c6b33fd33cd2089ba97d6112f44ef0ba
names    : symfony/process

autoload
psr-4
Symfony\Component\Process\ => .
exclude-from-classmap

requires
php ^5.5.9|>=7.0.8

Could it be that i don't have the right php version?
Yes I looked at it, but I don't see where the error comes from.

It's this line : 
`if (__CLASS__ !== static::class) {`

**Comment by NiR-** [comment]
What's your version of PHP?

**Comment by Jokrion** [comment]
PHP Version 5.3.3-7
I can't change it by myself, i'm not working on my own environment. Is there a way to use snappy with this version?

**Comment by NiR-** [comment]
Composer should automatically install the right versions. What's you php requirement in your composer.json ("php" dependency in `require` section)?

**Comment by alexpozzi** [comment]
Closed for inactivity.
Please reopen the issue if it's still relevant.
