### ISSUE TITLE
cover BUG

### ISSUE THREAD

**Issue by arriel96** [KnpLabs/snappy#300]
I'm tryng to create a document passing the html:

```
$snappy = new Pdf('wkhtmltopdf');
$snappy->setOption('cover','<h1>ok</h1>');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
echo $snappy->getOutputFromHtml('<h1>Bill</h1><p>You owe me money, dude.</p>',['encoding' => 'UTF8']);

```

but when i insert html direct the way the content, is replace by the cover , i believe that's a bug , because the other combinations (script+pagehtml,pagehtml+pagehtml,pagehtml+script) work's fine.

PS: I'm trying use the replace option to change fil things on the document(replace information on the cover(not shure if is possible) and the title of the page, bechause on default header it always show the name of temporari html)

**Comment by ToshY** [comment]
This bug still exists. Apparently it only works if you pass an URL as argument for the `cover` option. everything else breaks the document.
