### ISSUE TITLE
Exception in Controller: The exit status code '134' says something went wrong

### ISSUE THREAD

**Issue by rebbieboi** [KnpLabs/snappy#301]
Error:
Exception in Controller: The exit status code '134' says something went wrong:
stderr: "QXcbConnection: Could not connect to display 
Aborted

OS: Debian

**Comment by selfcatering** [comment]
Having faced same error I assume you've manually installed wkhtmltopdf and are referencing directly to that bin. I suggest you use the binary provided with composer, that fixed it for me.
