### ISSUE TITLE
PDF File Not Created - Error in PHP Log

### ISSUE THREAD

**Issue by RossAWaddell** [KnpLabs/snappy#305]
I'm using this simple code to try and generate a PDF from my HTML:

```
    use Knp\Snappy\Pdf;

    $snappy = new Pdf('/usr/local/bin/wkhtmltopdf');

//    $snappy->setOption('orientation', 'Landscape');
//    $snappy->setOption('page-size','Letter');
//    $snappy->setOption('print-media-type', true);
//    $snappy->setOption('encoding', 'utf-8');

    header('Content-Type: application/pdf');
    echo $snappy->getOutputFromHtml($html);
```
But the browser says 'The PDF document might not be displayed properly' and all I see is a blank screen. In my PHP error log I see:

> [10-Mar-2018 21:39:40 America/Toronto] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/symfony/process/Process.php on line 139

I know my HTML is fine because it renders perfectly if I remove the snappy code, and I've validated it through a few online resources. I know wkhtmlpdf works because this code executes properly:

`exec('/usr/local/bin/wkhtmltopdf https://www.google.ca/ wkhtmltopdf_mar10.pdf');`

**Comment by leeyuentuen** [comment]
what do you see on line 139 in de file?

/Users/rwaddell/Dropbox/htdocs/wonderfest/private/contest/include/vendor/symfony/process/Process.php on line 139

**Comment by RossAWaddell** [comment]
NetBeans 8.2 reports an error on line 139 of process.php, which is:

`public function __construct($commandline, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)`

> Error: unexpected '?'

**Comment by RossAWaddell** [comment]
Lots of debugging later and everything works fine. I did find, though, that even with absolute links to images on my hosted site (which work fine when I copy-and-paste into the address of a browser page) doesn't work - instead, I had to add the `<base>` tag in the `<head>` of the html and then make the links to the images relative to that. While this works, I will need to remember to update the `<base>` info when moving to production. Ultimately, I think the problem was with (a) where I had my `ob_get_clean()` call, and (b) the snappy code details:

```
    use Knp\Snappy\Pdf;
    
    $snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
    $snappy->setOption('orientation', 'Landscape');
    $snappy->setOption('page-size','Letter');
    $snappy->setOption('no-outline', true);
    $snappy->setOption('print-media-type', true);
    $snappy->setOption('no-background', true);
    $snappy->setOption('encoding', 'utf-8');
    
    $tmpPDFile = '../../../../private/contest/tmp/' . $entryNum . '_printout.pdf';
    $snappy->generateFromHtml($html, $tmpPDFile);
```

That worked.
