### ISSUE TITLE
PDF is not generated properly and returns The exit status code '1'

### ISSUE THREAD

**Issue by rebbieboi** [KnpLabs/snappy#306]
This is my code for generating the PDF:

```
$content    = $_POST['content'];
        $email      = $_POST['email_add'];
        $subject    = "test";
        $email_body = $_POST['email_body'];
        $from_email = "test@test.com";
        $from_name = "test@test.com";

        $html = '
            <!DOCTYPE html>
            <html>
            <head>
            <title>PDF</title>
              <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            </head>
            <body>
            '.$content.'
            </body>
        ';
        $snappy = new Pdf('/var/www/html/ems/crm/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64');
//        $snappy = new Pdf('/usr/bin/wkhtmltopdf');

        $pdf_name = $this->generateRandomString().'.pdf';

        $snappy->generateFromHtml($html, 'upload/'.$pdf_name);

        $mail = new PHPMailer();
        $mail->setFrom($from_email, $from_name);
        $mail->addAddress($email);
        $mail->addAttachment('upload/'.$pdf_name);
        $mail->isHTML(true);                                  // Set email format to HTML
        $mail->Subject = $subject;
        $mail->Body    = $email_body;

        if($mail->send()){
            echo 'Email Sent';
        }else{
            echo 'Email Failed';
        }
        exit;
```

The PDF is generated but not properly. The "$content" part of the PDF is not rendered as HTML and is displayed as text.

This is the errors:

> Sun Mar 18 09:46:02 2018 [13838][1][FATAL] Exception in Controller: The exit status code '1' says something went wrong:
> stderr: "Loading pages (1/6)
> [>                                                           ] 0%
> [======>                                                     ] 10%
> QSslSocket: cannot resolve CRYPTO_num_locks
> QSslSocket: cannot resolve CRYPTO_set_id_callback
> QSslSocket: cannot resolve CRYPTO_set_locking_callback
> QSslSocket: cannot resolve sk_free
> QSslSocket: cannot resolve sk_num
> QSslSocket: cannot resolve sk_pop_free
> QSslSocket: cannot resolve sk_value
> QSslSocket: cannot resolve SSL_library_init
> QSslSocket: cannot resolve SSL_load_error_strings
> QSslSocket: cannot resolve SSLv3_client_method
> QSslSocket: cannot resolve SSLv23_client_method
> QSslSocket: cannot resolve SSLv3_server_method
> QSslSocket: cannot resolve SSLv23_server_method
> QSslSocket: cannot resolve X509_STORE_CTX_get_chain
> QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
> QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
> QSslSocket: cannot resolve SSLeay
> QSslSocket: cannot call unresolved function CRYPTO_num_locks
> QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
> QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
> QSslSocket: cannot call unresolved function SSL_library_init
> QSslSocket: cannot call unresolved function SSLv23_client_method
> QSslSocket: cannot call unresolved function sk_num
> [========>                                                   ] 14%
> QSslSocket: cannot call unresolved function SSLv23_client_method
> QSslSocket: cannot call unresolved function SSL_library_init
> [============================================================] 100%
> Counting pages (2/6)                                               
> [============================================================] Object 1 of 1
> Resolving links (4/6)                                                       
> [============================================================] Object 1 of 1
> Loading headers and footers (5/6)                                           
> Printing pages (6/6)
> [>                                                           ] Preparing
> [============================================================] Page 1 of 1
> Done                                                                      
> Exit with code 1 due to network error: UnknownNetworkError
> QSslSocket: cannot call unresolved function CRYPTO_num_locks
> QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
> QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
> "
> stdout: ""
> command: /var/www/html/ems/crm/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy5aae3559cd0016.43845328.html' 'upload/MOwYOG8Xbp.pdf'.
> Sun Mar 18 09:46:02 2018 [13838][1][FATAL] backtrace:
> #0 /var/www/html/ems/crm/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(177): Knp\Snappy\AbstractGenerator->checkProcessStatus(1, '', 'Loading pages (...', '/var/www/html/e...')
> #1 /var/www/html/ems/crm/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(63): Knp\Snappy\AbstractGenerator->generate(Array, 'upload/MOwYOG8X...', Array, false)
> #2 /var/www/html/ems/crm/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(211): Knp\Snappy\Pdf->generate(Array, 'upload/MOwYOG8X...', Array, false)
> #3 /var/www/html/ems/crm/custom/modules/Documents/controller.php(117): Knp\Snappy\AbstractGenerator->generateFromHtml('\n            <!...', 'upload/MOwYOG8X...')
> #4 /var/www/html/ems/crm/include/MVC/Controller/SugarController.php(523): CustomDocumentsController->action_emailPDF()
> #5 /var/www/html/ems/crm/include/MVC/Controller/SugarController.php(491): SugarController->do_action()
> #6 /var/www/html/ems/crm/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()
> #7 /var/www/html/ems/crm/include/MVC/Controller/SugarController.php(373): SugarController->process()
> #8 /var/www/html/ems/crm/include/MVC/SugarApplication.php(105): SugarController->execute()
> #9 /var/www/html/ems/crm/index.php(52): SugarApplication->execute()
> #10 {main}

**Comment by alagiyanirav** [comment]
I have the same issue.
Any help?

**Comment by nogaent** [comment]
Have the same issue, pls help...

**Comment by Kingtree2009** [comment]
download to 0.12.2.1

**Comment by Kingtree2009** [comment]
degrade to 0.12.2.1

**Comment by alexpozzi** [comment]
It's probably related to the `wkhtmltopdf` binary version you are using.
Did you try to upgrade it?

I'm going to close the issue.
Please reopen the issue if it's still relevant.

**Comment by ricklambrechts** [comment]
Hi, today i got the same issue.
What helped for me was installing `libssl1.0-dev`.

[https://github.com/amra/DocumentationAsCode/issues/2#issuecomment-388613071](https://github.com/amra/DocumentationAsCode/issues/2#issuecomment-388613071)

**Comment by gulgulia17** [comment]
**If anyone still facing this issue and If you are on Ubuntu, try installing it without composer.**

````
sudo apt update
````
````
sudo apt install wkhtmltopdf -y
````
````
sudo cp /usr/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
````
