### ISSUE TITLE
Table rows doesn't break on multiple pages

### ISSUE THREAD

**Issue by karimh777** [KnpLabs/snappy#307]
If the table contents can't fit on the space left in the page the whole table is printed on a single page leaving a big white gap on the page before.

**Comment by alexpozzi** [comment]
I'm going to close the issue (as it's dating 2018).
Please reopen the issue if it's still relevant.

In case it's still relevant please share some more information about your environment, your code and the result you'd like to get. BTW it's probably an issue related to CSS/wkhtmltopdf config.
