### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by kironet** [KnpLabs/snappy#309]
Hi, I',m having a problem with this bundle.
I'm getting this "warning":

> Warning: file_put_contents(/tmp/knp_snappy5ad9b4ed742ef2.18808451.html): failed to open stream: No such file or directory

I tried run test command in console `wkhtmltopdf http://www.google.com /tmp/google.pdf` 
This command worked.

**Comment by CrixuAMG** [comment]
This is most likely a permission error, not with the package. If you `dd()` the file before saving it, you can most likely see that the `realPath` field is `null`. If that is the case, just fix the permissions on the `/tmp` folder.

**Comment by kironet** [comment]
Thanks.
Just changed /tmp to project cache directory.
