### ISSUE TITLE
Generate pdf without pagebreak

### ISSUE THREAD

**Issue by nieka** [KnpLabs/snappy#310]
Hello,

I would like to generate a pdf that does not consist out of multiple pages when there is not enough room on a default A4 page.

I tried to disable page break by adding the following code to my style sheet:
`
div {
    page-break-after: avoid !important;
    page-break-inside: avoid !important;
    page-break-before: avoid !important;
}
`
But when I generate the pdf it is still splitted into multiple pages. 

Is it even possible to disable page break complete when generating an pdf?

**Comment by ysd-wilson** [comment]
I am facing the same issue on CentOS. Any updates?
