### ISSUE TITLE
Base64 Image isn't displaying on PDF

### ISSUE THREAD

**Issue by mboudjouhali** [KnpLabs/snappy#311]
Hello, 

I'm actually using Symfony 3.4 + CMENGoogleCharts(v3.0.1) + Snappy (v1.0.4) .  
My problem : I am not able to display my base64 image into my PDF. The image is generated by CMENGoogleCharts using the "getImageURI()" from Google ([example](https://developers.google.com/chart/interactive/docs/printing)).  
  
But however, I'm able to display my image on my view (I don't get any errors). (ex :  `<div id="png_2"><img src="data:image/png;base64,gQIECAAIExBATC[.......]5ErkJggg=="></div>` ). 

There is my controller : 
```
[.....]
$html = $this->renderView('entretien/pdf.html.twig', array(
                'entretien' => $entretien,
                [ .... ]
            ));
            
            $filename = "file-".$entretien->getId().".pdf";
            
            //var_dump($html);die;
            
            return new PdfResponse(
                $this->get('knp_snappy.pdf')->getOutputFromHtml($html),
                $filename
            );
```

Am i missing something ?
Btw, my image is showing up in a "classic" return view. 
I'am creating "dynamically" those charts/images do you think the PDF is generated before my chart ? ( I personnally don't think so, because, when I var_dump($html). I can see all my image/charts. )

PS: Sorry for my bad english (:

**Comment by alexpozzi** [comment]
It's probably a `wkhtmltopdf` issue (see [here](https://stackoverflow.com/questions/25062224/wkhtmltopdf-not-rendering-base64-image) for example). Have you tried to upgrade it?

I'm going to close the issue (as it's dating 2018).
Please reopen the issue if it's still relevant.
