### ISSUE TITLE
Issue with FULLWIDTH WON SIGN (U+FFE6) symbol

### ISSUE THREAD

**Issue by halmai** [KnpLabs/snappy#314]
I work on a Laravel project which uses Snappy for creating PDF files. I am not sure if this is the place where I should report the bug, so please let me know if I should do it somewhere else. 

I have a html document containing korean currencies. Snappy produces a very strange result. After a long investigation, it turned out that Snappy seems to mishandles one of the korean won symbols. For some reason there are two won symbols:
- '￦' is FULLWIDTH WON SIGN (U+FFE6), it is not handled properly
- '₩' is WON SIGN (U+20A9) which it handled well.

The incorrectly handled wide symbol was created by a code snippet like this:

    // works on linux, after installing all the possible locales
    setlocale(LC_MONETARY, 'ko_KR.utf8'); 
    $html = money_format('%n', 123456.78);

As a work-around, I applied `$html = str_replace('￦', '₩', $html)` to fix the issue.

Here is a test $html to show the error:

    $html = '<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/></head><body><div>FULLWIDTH WON SIGN: ￦ WON SIGN: ₩</div></body></html>';

From this input, the generated PDF shows a square in place of the wide symbol and shows the correct won symbol in place of the narrow one.

**Comment by halmai** [comment]
Here is the result PDF:

[korean_won_symbols.pdf](https://github.com/KnpLabs/snappy/files/2015203/korean_won_symbols.pdf)

**Comment by alexpozzi** [comment]
Did you try installing a font supporting Korean characters on the server/container running your app?
See https://help.ubuntu.com/community/Fonts#Chinese.2C_Japanese.2C_and_Korean_Fonts

**Comment by halmai** [comment]
> Did you try installing a font supporting Korean characters...

No. :) 

This issue happened ~1.5 years ago, then we solved it with the above mentioned work-around. Since then, I haven't used Snappy.

**Comment by alexpozzi** [comment]
Ok, I’m gonna close the issue.
If installing a font supporting Korean characters will solve your issue please share it.

Thank you!
