### ISSUE TITLE
How to scale the image to appear on one page of the PDF.

### ISSUE THREAD

**Issue by mzohaiba** [KnpLabs/snappy#315]
How to scale the image to appear on one page of the PDF. If the image is higher than it is wide, include it in "portrait mode"; if the image is wider than it is high, include it in "landscape mode".

**Comment by alexpozzi** [comment]
I would say that it's more CSS responsibility than wkhtmltopdf responsibility.
BTW I need a little bit more information to be able to help you (like a page example).
I'm going to close the issue.
Please reopen the issue if it's still relevant.
