### ISSUE TITLE
Empty PDF when source is https

### ISSUE THREAD

**Issue by andremoens** [KnpLabs/snappy#318]
Hi,

When I try to generate a PDF from a https-url, the result is an empty PDF. When I use the same code with a http-url the code works fine. I googled and searched in the issue-list, but could not find a solution.

So:
  echo $snappy->getOutput('http://www.at5.nl/');
  $snappy->generateFromHtml('http://www.at5.nl/', '/home/admin/domains/domain.nl/pdf/test.pdf');

works fine.

  echo $snappy->getOutput('https://www.nu.nl/');
  $snappy->generateFromHtml('https://www.nu.nl/', '/home/admin/domains/domain.nl/pdf/test.pdf');

generates empty PDF.

Who knows how to solve this?

**Comment by samy** [comment]
The problem is related to wkhtmltopdf itself : 0.12.4 release doesn't support HTTPS resources.

So you need to install 0.12.5 release :
```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb \
&& dpkg -i wkhtmltox_0.12.5-1.stretch_amd64.deb
```
