### ISSUE TITLE
Merge pdf files

### ISSUE THREAD

**Issue by Franzimaibach** [KnpLabs/snappy#319]
Hi there,

I was wondering if there exists a function to merge several pdf files from different sources. 

Since I was curious about it, I implemented a merge function that works with ghostscript. The work for implementation was not too much and it works quite well. 

If such a function is not existing, would that be interesting to integrate it into your code as well?

Best,
Peter

**Comment by alexpozzi** [comment]
Thank you for offering it but IMHO this feature it's out of Snappy's scope.
