### ISSUE TITLE
Footer missing - QPainter::begin(): Returned false Error: Unable to write to temp location

### ISSUE THREAD

**Issue by eherrera** [KnpLabs/snappy#320]
Hello,
I'm trying to generate a pdf with KnpLabs/snappy in windows and **the footer is missing**.
**Logs:**
`Loading pages (1/6) [> ] 0% [======> ] 10% [==============================> ] 50% [============================================================] 100% QPainter::begin(): Returned false Error: Unable to write to temp location [======> ] 10% [==============================> ] 50% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) [======> ] 10% [==============================> ] 50% [============================================================] 100% Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1 Done`
**Generated command:**
`"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --lowquality --encoding "UTF-8" --load-error-handling "ignore" --load-media-error-handling "ignore" --footer-html "http://localhost/footer/footer_5b242af6e11f6.html" --footer-line "input.html" "output.pdf"`
**Version:**
wkhtmltox-0.12.4_msvc2015-win64.exe

From the command line it works fine.
Any Ideas?

**Comment by alexpozzi** [comment]
It seems you are having a permission issue here.
I would suggest you to verify that your web-server user has the rights to write in the configured temp folder.
