### ISSUE TITLE
Snappy PDF show the TOC for First heading in the html 

### ISSUE THREAD

**Issue by karthikrajender** [KnpLabs/snappy#322]
Hi Team

could you please help me on showing the table of contents for only heading's at first level, not for the heading inside the inner level

            'toc-depth'                    => null,
            'toc-font-name'                => null,
            'toc-l1-font-size'             => null,
            'toc-header-text'              => null,
            'toc-header-font-name'         => null,
            'toc-header-font-size'         => null,
            'toc-level-indentation'        => null,
            'disable-toc-links'            => null,
            'toc-text-size-shrink'         => null,

I check the parameters for TOC what is the value need to passed for each parameter

**Comment by qweluke** [comment]
@karthikrajender @0livier @pilot 
any news abut this issue? I am trying to do the same..

**Comment by qweluke** [comment]
@karthikrajender @pilot 
found a solution, here's an example: 
https://stackoverflow.com/questions/39846155/toc-level-2-styling-on-new-page-and-toc-options

**Comment by pilot** [comment]
@qweluke post from 2016, but seems should work. Use XSLT is another challenge lol.

Do you try it? Share feedback pls.

**Comment by qweluke** [comment]
@pilot yes, I have used solution from my previous post and it is working fine.
`toc-depth` was in some old wkhtmltopdf version which was dropped and now `XSLT` is the only way to achieve this
