### ISSUE TITLE
Slow Generation

### ISSUE THREAD

**Issue by nsraven34** [KnpLabs/snappy#324]
I have an invoice service where the invoices can be converted to PDF. The PDF generation works great, but on the FIRST generation of each users session it takes around 20 seconds to generate the PDF. Upon successive generation it generates in about 1-2 seconds. Why, or how can I fix the first generation time?

**Comment by xlkit456852** [comment]
I have the same problem...

**Comment by Midas-ArpitaS** [comment]
I have generate pdf , but takes around 10 -15t seconds in IE EDge

**Comment by alexpozzi** [comment]
I'm afraid that it's not a Snappy related issue.
Does it happens on other pages as well or it's just related to that specific page?

I'm closing this issue.
If it's still relevant, please answer this comment with the required details.
