### ISSUE TITLE
Sometimes wrong size of PDF Output stream

### ISSUE THREAD

**Issue by jofecolella** [KnpLabs/snappy#325]
Hello! I am having a weird problem. I have laravel 5.4 in Ubuntu 14.04. Sometimes when I generate the PDF the size of the pdf's content is wrong and sometimes is OK. Just reload this link a few times, in less than 10 times you will see what I mean:

http://nocnocgroup.com/token/OL1000059.1223241

Hope you can help me,

Thank you

**Comment by alexpozzi** [comment]
Hi,
Is this issue still relevant? 
I tried to replicate the issue without luck.
If you found a solution please share it!
