### ISSUE TITLE
[solved] BUG with fonts smoothing

### ISSUE THREAD

**Issue by jhabai** [KnpLabs/snappy#326]
Hi,
I'm using Knp\Snappy\Pdf ("h4cc/wkhtmltopdf-amd64": "0.12.*")

My pdf are well generated, but something goes wrong with special fonts, text are destroyed.
![pdf font destroy](https://user-images.githubusercontent.com/7123997/44727074-79081c80-aad9-11e8-8b8c-f9f1a28ba9da.JPG)

``
/* poppins-300 - latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 300;
  src: url('#{$public-path-fonts}/poppins-v5-latin-300.woff2') format('woff2'), /* Super Modern Browsers */
  url('#{$public-path-fonts}/poppins-v5-latin-300.woff') format('woff'); /* Legacy iOS */
}

/* poppins-regular - latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: url('#{$public-path-fonts}/poppins-v5-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
  url('#{$public-path-fonts}/poppins-v5-latin-regular.woff') format('woff'); /* Legacy iOS */
}

/* poppins-600 - latin */
@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 600;
  src: url('#{$public-path-fonts}/poppins-v5-latin-600.woff2') format('woff2'), /* Super Modern Browsers */
  url('#{$public-path-fonts}/poppins-v5-latin-600.woff') format('woff'); /* Legacy iOS */
}

/* Kosova*/
@font-face {
  font-family: 'Kosova';
  font-style: normal;
  font-weight: 600;
  src: url('#{$public-path-fonts}/Kosova.woff') format('woff'); /* Legacy iOS */
}
``
Do you know what is going on ?

**Comment by jhabai** [comment]
Does someone else have this problem ?

**Comment by jhabai** [comment]
using svg fonts solved the problème

**Comment by yaronel** [comment]
Can you share the @font-face declaration using svg?
It did not work for me.

**Comment by jhabai** [comment]
```
@font-face {
  font-family: 'lato';
  font-style: normal;
  font-weight: 300;
  src:
          url('#{$public-path-fonts}lato-v14-latin-regular.svg#Poppins') format('svg'),
          url('#{$public-path-fonts}lato-v14-latin-regular.woff2') format('woff2'),
          url('#{$public-path-fonts}lato-v14-latin-regular.woff') format('woff'); /* Legacy iOS */
}
```

**Comment by yaronel** [comment]
Thanks, it actually did work.
