### ISSUE TITLE
Does this support flexbox ?

### ISSUE THREAD

**Issue by bedus-creation** [KnpLabs/snappy#327]
I got into problem with bootstrap 4 while printing columns. when i debug that It generates the pdf as same as when I remove the flex property from the bootstrap css.

**Comment by alexpozzi** [comment]
This issue is related to `wkhtmltopdf` and not to Snappy so I would suggest you to open an issue on [`wkhtmltopdf` repo](https://github.com/wkhtmltopdf/wkhtmltopdf).

See also https://github.com/KnpLabs/snappy/issues/229
