### ISSUE TITLE
Error 126. Permission denied

### ISSUE THREAD

**Issue by KSneijders** [KnpLabs/snappy#345]
Hey, I saw this [issue](https://github.com/KnpLabs/snappy/issues/260):

And a little further down you mentioned: 
> Could you add executable perm to the binary? (on your server: `chmod +x vendor/h4cc/wkhtmltopdf-amd64-centos7/bin/wkhtmltopdf-amd64`)

I have the same error and was wondering how'd I fix this issue and how to add something to the binary
Error:
```
Fatal error:  Uncaught RuntimeException: The exit status code '126' says something went wrong:
stderr: "sh: ../lib/wkhtmltopdf/bin/wkhtmltopdf.exe: Permission denied
"
stdout: ""
command: ../lib/wkhtmltopdf/bin/wkhtmltopdf.exe --lowquality --margin-bottom '0' --margin-left '15' --margin-right '15' --margin-top '20' --load-error-handling 'ignore' --footer-html 'pdf/footer.html' --header-html 'pdf/header.html' '/tmp/knp_snappy5c38d7344790e8.26250739.html' '/tmp/knp_snappy5c38d73447b0b4.84383128.pdf'. in /var/www/vhosts/onecrm.nl/www/pre-release/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php:378
Stack trace:
#0 /var/www/vhosts/onecrm.nl/www/pre-release/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(177): Knp\Snappy\AbstractGenerator->checkProcessStatus(126, '', 'sh: ../lib/wkht...', '../lib/wkhtmlto...')
#1 /var/www/vhosts/onecrm.nl/www/pre-release/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(63): Knp\Snappy\AbstractGenerator->generate(Array, '/tmp/knp_snappy...', Array, false)
#2 /var/www/ in /var/www/vhosts/onecrm.nl/www/pre-release/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php on line 378
```

**Comment by alexpozzi** [comment]
Can you give us more details about your environment and your configuration?
Sounds like you are trying to execute an `.exe` file on a Linux env.

I suggest you to verify that your php process can access `wkhtmltopdf` executable at the path you configured and that it has the rights to execute it.

**Comment by KSneijders** [comment]
It's been a while since I posted this so an't remember exactly. But as far as I know I left `KnpLabs/snappy` for what it was and just used `WKHTMLTOPDF ` command line. 
I'm not if it was a Linux machine, might have been. Was an external server out of my control.
