### ISSUE TITLE
Merge multiple PDF sources

### ISSUE THREAD

**Issue by PaulCombal** [KnpLabs/snappy#348]
Hello,

I would like to know if it is possible to merge multiple PDFs from different sources: a generated one and a custom uploaded one.

As pointed out in the readme, you can do this:

```
$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
echo $snappy->getOutput(array('http://www.github.com','http://www.knplabs.com','http://www.php.net'));```
```
But is it possible to achieve something that would look like this:

```php
/** @var UploadedFile $uploadedpdf */
$uploadedpdf = $request->files->get('supplement.pdf');
$normalpdf = $snappy->getOutputFromHtml($html);
$finalPdf = $snappy->getOutput($uploadedPdf, $normalPdf);
```
Thank you

**Comment by alexpozzi** [comment]
Hi,
The feature you are describing is not supported by this library and IMHO it's out of its scope.
You can use Snappy to generate the pdfs you need and merge them later using utilities like Ghostscript.
