### ISSUE TITLE
Version 1.0 is not working at all!

### ISSUE THREAD

**Issue by gesior** [KnpLabs/snappy#351]
I've updated my app to version 1.0, it installed 1.0.0 and this version does not work at all.
It calls 'setOptions' before setting $this->logger and 'setOption' calls logger!

https://github.com/KnpLabs/snappy/blob/v1.0/src/Knp/Snappy/AbstractGenerator.php#L50
https://github.com/KnpLabs/snappy/blob/v1.0/src/Knp/Snappy/AbstractGenerator.php#L52

Can you remove tag for version that does not work at all from GitHub?

**Comment by alexpozzi** [comment]
I'm sorry but we are not removing releases (it was created on 2017 and quickly fixed).
BTW, as far as I saw from the code, the bug happens just if you specify the options when instantiating the service.
