### ISSUE TITLE
not running on windows 

### ISSUE THREAD

**Issue by konwww** [KnpLabs/snappy#352]
Error message :
`The exit status code '1' says something went wrong: stderr: "Unknown long argument --lowquality Name: wkhtmltoimage 0.12.5 (with patched qt) Synopsis: wkhtmltoimage [OPTIONS]... 
 Description: Converts an HTML page into an image, General Options: --crop-h Set height for cropping --crop-w Set width for cropping --crop-x Set x coordinate for cropping --crop-y Set y coordinate for cropping -H, --extended-help Display more extensive help, detailing less common command switches -f, --format Output file format --height Set screen height (default is calculated from page content) (default 0) -h, --help Display help --license Output license information and exit --log-level Set log level to: none, error, warn or info (default info) --quality Output image quality (between 0 and 100) (default 94) -q, --quiet Be less verbose, maintained for backwards compatibility; Same as using --log-level none -V, --version Output version information and exit --width Set screen width, note that this is used only as a guide line. Use --disable-smart-width to make it strict. (default 1024) Contact: If you experience bugs or want to request new features please visit " stdout: " " command: D:/wkhtmltopdf/bin/wkhtmltoimage.exe --lowquality "http://www.baidu.com" "D:/a.pdf". 0.459204s ShowPageTrace`

**The command :"D:/wkhtmltopdf/bin/wkhtmltoimage.exe --lowquality "http://www.baidu.com" "D:/a.pdf"" is wrong ?**
![image](https://user-images.githubusercontent.com/34157376/59148770-8fb3aa80-8a3f-11e9-8c68-12e0e99e0a4b.png)

**Comment by alexpozzi** [comment]
As I can see from your log the command used to generate the pdf is using `wkhtmltoimage` instead of `wkhtmltopdf` (the executable that should be used to generate pdfs).
I suggest you to check on your code to ensure that you configured the right executable.
