### ISSUE TITLE
the binary returns "Success" and knp snappy expects empty string

### ISSUE THREAD

**Issue by verybigelephants** [KnpLabs/snappy#354]
hello, when trying to run the pdf conversion i am getting this error:

```
The exit status code '126' says something went wrong:
stderr: "sh: /usr/local/bin/wkhtmltopdf: Success
"
stdout: ""
command: /usr/local/bin/wkhtmltopdf --lowquality '...inputfile...' '...outputfile...'.
```
i have looked in the abstract generator and it shows that it expects status code 0 and empty string https://github.com/KnpLabs/snappy/blob/master/src/Knp/Snappy/AbstractGenerator.php#L377

but the excutable shows status code 126 and string "Success" and i don't know where is the problem now

**Comment by alexpozzi** [comment]
Hello!
What happens if you run the command manually via command line? Do you have the same result?
Can you share a little more details about your environment?

I'd suggest you to reinstall wkhtmltopdf executable and check on its permissions.
