### ISSUE TITLE
buildCommand method of generator outputs float values locale-aware

### ISSUE THREAD

**Issue by finwe** [KnpLabs/snappy#357]
In an environment with cs_CZ locale, arguments of the command are being output as locale aware, which is a problem with decimal page margins:

```
$options = [
	'margin-top'    => 25.4,
	'margin-right'  => 19.1,
	'margin-bottom' => 25.4,
	'margin-left'   => 19.1,
];
```

becomes 

     --margin-bottom '25,4' --margin-left '19,1' --margin-right '19,1' --margin-top '25,4'

Yes, the values can be specified as strings, it would still be nice if this was handled internally.

**Comment by alexpozzi** [comment]
Hello,
Would you mind opening a PR for that?
