### ISSUE TITLE
Download PDF without saving it on server HDD

### ISSUE THREAD

**Issue by Zmove** [KnpLabs/snappy#358]
Hello,

I'm working on a system that need to generate PDF depending on some user inputs.

Everything works well except that actually, PDF are saved on the server disk, then, downloaded by users.

For security reasons (as PDF contains some private datas), I would like to generate the PDF on demand (in memory ?) then allow users to download it, but never save it in the server (or, if not possible, save it the time to download it but remove it just after).

Is it possible to do something like that ?

Thank you

**Comment by alexpozzi** [comment]
If you use `getOutput` or `getOutputFromHtml` the generated pdf is returned as a string. 
This methods save the pdf to a temporary file that will be deleted at the end of the request.

See example code:
```
$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
echo $snappy->getOutput('http://www.github.com');
```
