### ISSUE TITLE
Set PDF Properties

### ISSUE THREAD

**Issue by nasirkhan** [KnpLabs/snappy#359]
Is there any way to set the PDF properties like Author, Subject and so on?

**Comment by alexpozzi** [comment]
AFAIK Author and Subject are not supported by this library because wkhtmltopdf does not support them.
See related [wkhtmltopdf issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2000)
See [wkhtmltopdf doc](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)
