### ISSUE TITLE
RuntimeException  The exit status code '1' says something went wrong: stderr: "The system cannot find the path specified.

### ISSUE THREAD

**Issue by anandnaga** [KnpLabs/snappy#361]
am install laravel 5.6

try to install snappy pdf plugin.

allready tried set  providers and aliases but the page show some error i dont know how can i fix this

**Comment by alexpozzi** [comment]
Hello,
I suggest you to check that the `wkhtmltopdf` executable exists and is accessible at the path you specified.

For example, for the following code, you should check that `/usr/local/bin/wkhtmltopdf` exists:
```
$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
```
