### ISSUE TITLE
openssl issues - upgrade to 0.12.5

### ISSUE THREAD

**Issue by thejacer87** [KnpLabs/snappy#374]
i've run into issues with ssl stuff: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

apparently upgrading to 0.12.5 should help

**Comment by alexpozzi** [comment]
Thank you for reporting it.
Did you try to upgrade `wkhtmltopdf` to v0.12.5? 
Did it solve your issue?

**Comment by thejacer87** [comment]
@alexpozzi yes, when i manually install 0.12.5 it worked. do you have a timeline on a 0.12.5 release and/or dev branch

**Comment by alexpozzi** [comment]
The version of `wkhtmltopdf` is not related to Snappy, you can install what version you want.

**Comment by thejacer87** [comment]
ah sorry, for those that may stumble this way, here is the 0.12.5 issue in the h4cc repo (ie where the bin for wkhtml comes from )

https://github.com/h4cc/wkhtmltopdf-amd64/issues/38

**Comment by AndreaGreco** [comment]
`uname -a`:
Linux 5.3.11-200.fc30.x86_64 #1 SMP Tue Nov 12 19:25:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

wkhtmltopdf -version
wkhtmltopdf 0.12.5
```
QSslSocket: cannot resolve CRYPTO_num_locks                  ] 2%
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
```
Not working over last Fedora, same error.
