### ISSUE TITLE
How to encrypt PDF, so no one can open it in Microsoft Word

### ISSUE THREAD

**Issue by nisharg007** [KnpLabs/snappy#393]
How to encrypt pdf so no one can open it in microsoft word, I don't want a password in PDF, only that type of encryption so no one can open it and edit it.

If possible can you also tell me, how can I reduce my PDF file size.

I am at latest version of snappy.

**Comment by alexpozzi** [comment]
AFAIK `wkhtmltopdf` doesn't support pdf encryption so, as a consequence, Snappy doesn't either.
You can generate the pdf with Snappy and then use another tool to encrypt it after.

**Comment by NishargShah** [comment]
ohk

**Comment by nisharg007** [comment]
ohk, thanks!!
