### ISSUE TITLE
background image does not show

### ISSUE THREAD

**Issue by johannesvlot** [KnpLabs/snappy#394]
I am generating a pdf and i'd like to have a background image on the whole pdf.

Outputting the pdf works fine only the background doesn't show.

I tried:

`<body style="background-image: {{ absolute_url(asset('img/signatures/'~  workOrder.id ~'.png')) }}">`

In style tags:
`<style>
    body {
    background-image: {{ absolute_url(asset('img/signatures/'~  workOrder.id ~'.png')) }}
    }
</style>`

(tried without absolute url's too)

I don't see anything of the background image.

please help thanks

**Comment by alexpozzi** [comment]
Hello,
Which version of `wkhtmltopdf` are you using?
Are you sure your php process can access the url you are providing as background image?
