### ISSUE TITLE
executeCommand Error

### ISSUE THREAD

**Issue by gunnzhao** [KnpLabs/snappy#400]
AbstractGenerator.php line:528

Process class expected type 'array'. Found 'string'

![image](https://user-images.githubusercontent.com/9549996/88357307-67028780-cd9d-11ea-8477-d5a6c6d819e1.png)

**Comment by alexpozzi** [comment]
It depends on the Symfony version you are using, that method was used to support legacy Symfony versions but your code shouldn't run that line but, instead, `Process::fromShellCommaneline`.
There is already an opened PR that refactors that https://github.com/KnpLabs/snappy/pull/398.
