### ISSUE TITLE
Possibility to use `docker run` instead of a local binary

### ISSUE THREAD

**Issue by icaroscherma** [KnpLabs/snappy#401]
This issue is a clone of: https://github.com/barryvdh/laravel-snappy/issues/384

I'm using a workaround of encapsulating the whole Application on the same container that has wkhtmltopdf, but what I really wanted was to point the wkhtmltopdf binary to something like:
`docker run surnet/alpine-wkhtmltopdf:3.10-0.12.5-full`

And keep using the regular snappy output functions as usual.

**Comment by alexpozzi** [comment]
I have to admit that I have no idea, I would say yes. 
Maybe not directly using `docker run surnet/alpine-wkhtmltopdf:3.10-0.12.5-full` as the binary path but writing a script that does that and use that script as binary path?

Did you give it a try? Sorry for not being able to help more but I don't have a local non-dockerized LAMP to be able to test it.

**Comment by icaroscherma** [comment]
I think it should work with something like:
`docker run surnet/alpine-wkhtmltopdf:3.10-0.12.5-full google.com - 2>&1`
but instead of `google.com` it's the HTML or website we pass as an argument, because this command returns the content of the PDF.
I will take a deeper look and try some modifications on the vendor if needed, then PR it. =)

**Comment by alexpozzi** [comment]
Before you work on some changes on Snappy please comment this issue with the changes you have in mind.
I'm not so sure it would make sense for this project to support this case.

Closing the issue for now.
