### ISSUE TITLE
Download big and multiple pdf

### ISSUE THREAD

**Issue by RayhanYulanda** [KnpLabs/snappy#403]
Should I save all generated PDF-files to server and then create a zip-archive of all the PDF files? Or i can download it without save it to server (directly from tmp)?
Or is there another option?

**Comment by alexpozzi** [comment]
Hi,
It's a little difficult to give you a "right" answer without knowing all the details as there are too many variables to take into consideration (it's also a little outside of this library scope the way you deal with generated PDFs).

If you want to generate a PDF and you don't need to persist it on your filestore/database you can use the example described in the README to return it to the client and trigger the download.

https://github.com/KnpLabs/snappy#download-the-pdf-from-the-browser
```
$snappy = new Pdf('/usr/local/bin/wkhtmltopdf');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
echo $snappy->getOutput('http://www.github.com');
```
