### ISSUE TITLE
What's the difference between stream and download?

### ISSUE THREAD

**Issue by RayhanYulanda** [KnpLabs/snappy#404]
Can you explain the difference is?

**Comment by alexpozzi** [comment]
Are you sure you selected the right repository for this question?

**Comment by RayhanYulanda** [comment]
@alexpozzi yes. Because i see in this package there is function stream and download

**Comment by alexpozzi** [comment]
Can you show me where?
By the way, this is out of the scope of this library, I suggest you to search for it, there are great articles out there explaining in details the difference between them (something like https://www.sitepoint.com/php-streaming-output-buffering-explained).
