### ISSUE TITLE
Exception: The process has been signaled with signal "11"

### ISSUE THREAD

**Issue by raenk** [KnpLabs/snappy#406]
Hi,

I'm running some tests and this is how it goes:

Case 1:
`header('Content-Type: application/pdf');`
`header('Content-Disposition: attachment; filename="file.pdf"');`
`echo $this->snappy->getOutput('http://www.github.com');`

Result: `Exception: The process has been signaled with signal "11"`

Case 2:
`$this->snappy->setOption('disable-javascript', true);`
`$this->snappy->generateFromHtml($pdf_template, $pdf_full_path);`

Result: `Exception: The process has been signaled with signal "11"`
Considerations: The variables passed are correct (html content and full path to the final file to write). The html is a complete html page, with images and CSS linked files as any other webpage, but "leaner" for print purposes.

Case 3:
However, when I try with an extremely simple HTML, it works:
`$pdf_template = "<h1>Hello</h1>";`
`$this->snappy->setOption('disable-javascript', true);`
`$this->snappy->generateFromHtml($pdf_template, $pdf_full_path);`

So, this makes me think there's nothing wrong at the server side (binary, PHP version, etc). Here's the server setup:

PHP 7.4.12 with Opcache (I have tried without Opcache and same results)
wkhtmltopdf 0.12.4 (with patched qt)

I think something within my HTML is causing this. However, it throws me away the fact that the docs give as an example www.github.com to turn it into PDF and doesn't work either.

Any ideas?

Thanks

**Comment by raenk** [comment]
Well, further investigation has lead me to an issue with wkhtmltopdf 0.12.4 calling HTTPS links. It appears to be broken.

Testing with an HTML file directly on CLI throws this:
```
QSslSocket: cannot resolve CRYPTO_num_locks 
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
```
Clearly something wrong with SSL. This lead me to theses links:
[https://github.com/amra/DocumentationAsCode/issues/2](url)
[https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001](url)

So, basically if you run into this issue, you need to upgrade to 0.12.5 or try some workarounds like the mentioned in the links.

I haven't solved it. But I'm pretty sure that I found the solution. I'll update this when confirmed.

**Comment by raenk** [comment]
Confirmed. Upgrade wkhtmltopdf to 0.12.5 or greater.

**Comment by alexpozzi** [comment]
Thanks @raenk for detailing this and providing a solution, this is as valuable as a contribution!
