### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by esurov** [KnpLabs/snappy#410]
Hi! Does this package support php7.4? We're migrating our app to php7.4 and need to know that our dependencies are good. I found no information on php7.4 support, last version in travisci is 7.3.

**Comment by alexpozzi** [comment]
Hi,
Yes, this package supports php7.4, I'm gonna update the tests as soon as I can.

**Comment by RenaudPERRAI** [comment]
Hi,
I use snappy with PHP 7.4.8 and it's work fine (also with symfony 4.4.x).

**Comment by esurov** [comment]
Perfect! Thanks for letting know!
