### ISSUE TITLE
Issue with enabling external links in pdf

### ISSUE THREAD

**Issue by chrisijoyah** [KnpLabs/snappy#411]
I'm trying to enable external links in a pdf so that anchor tags are clickable using `->setOption('enable-external-links')` but when pdfs are generated the no links are clickable. Do I need to disable any additional options?

```
$pdf = new SnappyPdf::loadHtml($html)
$pdf->setOption('enable-external-links')
...
```

**Comment by alexpozzi** [comment]
Hello,
the `enable-external-link` it's enabled by default on wkhtmltopdf so you shouldn't even have to specify it.
Can you give a little bit more information about the html you give as input and the version of the different component you use (ex. snappy and wkhtmltopdf)?
The only thing I can think of are some issues related to the wkhtmltopdf binary you are using.

**Comment by chrisijoyah** [comment]
@alexpozzi I think this is more than likely a binary version issue in that case as you mentioned the `enable-external-link` option should be enable by default.

**Comment by alexpozzi** [comment]
Let me know if you solve it. 
In case you need help just reply with a little more information (or else it's difficult to try to replicate it) and I'll try to help you :wink: 
On my side I can confirm you that I was able to generate links using the latest `wkhtmltopdf` binary version on the latest `php:7.4-fpm` Docker image.

I'm gonna close the issue for now but I'll re-open it in case it will be needed.
