### ISSUE TITLE
Image dimensions change automatically

### ISSUE THREAD

**Issue by yaseenolive** [KnpLabs/snappy#412]
Hello,
i am using laravel snapy and its working fine but the recent issue i faced when i am going to add image in PDF its changing image dimension auto can you please guide what will be the issue?
thanks in advance

**Comment by alexpozzi** [comment]
Hello,
it's difficult to say without having an example code to reproduce the issue.
Can you please provide one? As a first hint I would tell you to check on your css, depending on the wkhtmltopdf binary version you use you might have some non-supported properties (like flexbox).
