### ISSUE TITLE
Unknown long argument --lowquality Name: wkhtmltoimage 0.12.6 (with patched qt)

### ISSUE THREAD

**Issue by romeldev** [KnpLabs/snappy#415]
hello, I have this error when generating the pdf, it works fine on the server (ubuntu) but it fails on windows

**Comment by alexpozzi** [comment]
Hello,
It seems more an issue of your binary more than a Snappy issue.
If you manually run wkhtmltoimage with the `--lowquality` parameter from the Windows shell does it work?
Are you sure your php process uses the right wkhtmltoimage binary (maybe you ave multiple binary installed on your server).

**Comment by romeldev** [comment]
the error was mine as the --lowquality parameter is used with wkhtmltopdf
and not with wkhtmltoimage. Thanks
