### ISSUE TITLE
the quote button no longer appears

### ISSUE THREAD

**Issue by HaleluiaLuis** [KnpLabs/snappy#416]
Hi dear, I changed the template of my website, and the button to perform the option to download the quote stopped working.
can you help me with this please?
I need a lot!

**Comment by alexpozzi** [comment]
Hello,
It's difficult to help without having more context.
Can you send a reproducible example of the issue you are having?

Thanks!

**Comment by alexpozzi** [comment]
I never worked on Magento but, are you sure that you are on the right library repository?
Snappy itself doesn't provide any module for Magento (what youa re looking for it's probably another library that's using Snappy).
This library its providing an API to generate pdfs/images from an input HTML, all the implementation on top of it (views, etc..) as to be implemented by you.
