### ISSUE TITLE
Permission denied, unlink

### ISSUE THREAD

**Issue by rafaelgonzagag** [KnpLabs/snappy#417]
<br />
  <b>Fatal error</b>:  Maximum execution time of 30 seconds exceeded in <b>C:\Users\Uzer\bioacesso\mod\bioacesso\vendor\symfony\process\Pipes\WindowsPipes.php</b> on line <b>143</b><br />
  <br />
  <b>Fatal error</b>:  Uncaught exception 'ErrorException' with message 'unlink(C:\Users\Uzer\bioacesso\mod\bioacesso\public\tmp_proccess\knp_snappy6064db83e40c65.42814204.html): Permission denied' in C:\Users\Uzer\bioacesso\mod\bioacesso\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php:659
  Stack trace:
  #0 [internal function]: Slim\Slim::handleErrors(2, 'unlink(C:\\Users...', 'C:\\Users\\Uzer\\b...', 659, Array)
  #1 C:\Users\Uzer\bioacesso\mod\bioacesso\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php(659): unlink('C:\\Users\\Uzer\\b...')
  #2 C:\Users\Uzer\bioacesso\mod\bioacesso\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php(430): Knp\Snappy\AbstractGenerator-&gt;unlink('C:\\Users\\Uzer\\b...')
  #3 [internal function]: Knp\Snappy\AbstractGenerator-&gt;removeTemporaryFiles()
  #4 {main}
    thrown in <b>C:\Users\Uzer\bioacesso\mod\bioacesso\vendor\knplabs\knp-snappy\src\Knp\Snappy\AbstractGenerator.php</b> on line <b>659</b><br />

Usage:

        $this->dirwkhtmltopdf = '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"';
        $dataFile = date('zhisu');

        $snappy = new Pdf($this->dirwkhtmltopdf);
		
        $snappy->generateFromHtml('<h1>Bill</h1><p>You owe me money, dude.</p>', '/tmp/bill-123.pdf');
		echo "teste";exit();
        header('Content-Type: application/pdf; charset=utf-8');
        header('Content-Disposition: attachment; filename="'.$dataFile.'.pdf"');
        readfile('tmp/'.$dataFile.'.pdf');

**Comment by alexpozzi** [comment]
I suggest you to check that your PHP service has all the right access to the file is trying to delete.
The message seems pretty clear `Permission denied`.
