### ISSUE TITLE
Can't load CSS

### ISSUE THREAD

**Issue by NicolasSDuoc** [KnpLabs/snappy#419]
Hello, im trying to load some custom css and Bootstrap css to an html file, but they don't get loaded, can someone help me with this?

I'm using symfony 5.

Here is the header on the html.twig file:

```html
<link href="{{ absolute_url(asset('css/style.min.css'))}}" rel="stylesheet">
<link href="{{ absolute_url(asset('assets/libs/bootstrap/dist/css/bootstrap.min.css'))}}" rel="stylesheet">
```

and here is the controller:
```php

$pdf = $this->renderView('guia\pdf.html.twig', ['gdets'=>$gdets,'guia'=>$e_guia,'movmsg'=>$mov_mensaje]);

        $filename = 'test.pdf'
        return new PdfResponse(
            $this->knpSnappyPdf->getOutputFromHtml($pdf),
            $filename
        ); 
```

i have tried with absolute url, putting http://localhost...bootstrap.css and the cdn link but it doesn't work.

Any help really appreciated :)

**Comment by alexpozzi** [comment]
Hello,
I suggest you to try to run the wkhtmltopdf command manually (like `wkhtmltopdf YOUR_PAGE_URL`) and see if, with the verbose option on, you'll get more information.
It's hard to say what's happening here without Symfony + web server logs as, this issue, it can be caused by different causes.

**Comment by DonaldEtien** [comment]
Hello, I have the same problem with laravel. On the other hand, the colors are displayed on my mac. Has anyone found the solution?

**Comment by NicolasSDuoc** [comment]
> 
> 
> Hello, I have the same problem with laravel. On the other hand, the colors are displayed on my mac. Has anyone found the solution?

Hi, i ended up using Bootstrap 3, i read somewhere that flex doesnt work on wkhtmltopdf, so i had to do the document again with bs3, maybe you can try that

**Comment by lostfocus** [comment]
It's probably that - wkhtmltopdf is a pretty old rendering engine, newer CSS stuff isn't working.
