### ISSUE TITLE
Header and footer in each page

### ISSUE THREAD

**Issue by bettinz** [KnpLabs/snappy#422]
Hello, is it possible to add header and footer to each page and not in the first/last page?

edit: I'm using the integration with symfony 😄 

Thanks 🙏

**Comment by alexpozzi** [comment]
Hello,
I'm afraid that the only way to do it with this library is to generate different PDFs for the first page, for the middle pages and for the last page and then merge them together using tools like Ghostscript.

**Comment by bettinz** [comment]
Thank you @alexpozzi , what I'm trying to do is to add page number in the footer as explained here:
https://github.com/KnpLabs/KnpSnappyBundle/issues/286

If I've to generate different PDFs I think the page number will be wrong. Am I right?
Thanks

**Comment by eved42** [comment]
Hello,

Yes this is possible. Create 3 views, one for header, one for footer and one for content.
Each view needs to be a "complete" HTML page with a `<!DOCTYPE html>` at the begining of the file, and with `<html>`, `<head>` and `<body>` tags.

Then, you just need to specify the header and footer to Knp Snappy  and that's all.

```
// HTML content
$header = $this->renderView('header.html.twig');
$footer = $this->renderView('footer.html.twig');
$html = $this->renderView('content.html.twig');

// PDF to download
return new PdfResponse(
    $this->get('knp_snappy.pdf')->getOutputFromHtml($html, array(
        'header-html' 	=> $header,
        'footer-html' 	=> $footer
    )), 'file.pdf'
);
```

**Comment by diegodario88** [comment]
Hello,

by the way, how can I generate header/footer only for specific pages ?
