### ISSUE TITLE
Javascript Not Working

### ISSUE THREAD

**Issue by wichaksono** [KnpLabs/snappy#428]
i trying to write some javascript on my code

`<?php
require __DIR__ . '/vendor/autoload.php';

use Knp\Snappy\Pdf;

header('Content-Type: application/pdf');
#header('Content-Disposition: attachment; filename="file.pdf"');

$snappy = new Pdf();
$snappy->setBinary(__DIR__ . '/wkhtmltox/bin/wkhtmltopdf.exe');
$snappy->setOption('enable-javascript', true);
$snappy->setOption('javascript-delay', 13500);
$snappy->setOption('enable-smart-shrinking', true);
$snappy->setOption('no-stop-slow-scripts', true);
echo $snappy->getOutput('http://localhost/cv/tpl/test.html', [
    'margin-top'    => 0,
    'margin-right'  => 0,
    'margin-bottom' => 0,
    'margin-left'   => 0,
    'orientation' => 'portrait',
    'page-size' => 'A4',
    'no-outline'    => true,
]);
`

`<script type="text/javascript">
			var elm = document.getElementById("body");
			let h = elm.offsetHeight;
			document.getElementById("iii").innerHTML += h;
		</script>

<body id="body">
...
<div id="iii">the height </div>
...
</body>`

whats wrong in my code?

**Comment by wichaksono** [comment]
hi, thank for reply.

in my project i want to make some pretty pdf reporting, where the report is to long, the pdf output will be create new page, but now the page is not pretty.

i think can use javascript to count page height and comparing with total height of divs, when total height > page height, last div will be move to  new page.
iwant
![image](https://user-images.githubusercontent.com/11472981/131200554-ac036faf-6d46-441a-8bd3-726a740b232e.png)

but now
![image](https://user-images.githubusercontent.com/11472981/131200531-372a07c4-af5a-4c30-bff6-1d1ee9996f75.png)

**Comment by alexpozzi** [comment]
I think your issue is more of a CSS issue. I'm not a CSS master but having done a quick search on Google I found that you have the `break-inside` property that might help you achieving what you want.
See https://stackoverflow.com/questions/907680/css-printing-avoiding-cut-in-half-divs-between-pages.
I'm gonna close the issue as this is not really a Snappy issue but more an issue in your CSS or, in case,  a wkhtmltopdf issue.
