### ISSUE TITLE
Symfony\Component\Process\Exception\ProcessTimedOutException on PDF generation

### ISSUE THREAD

**Issue by SilverBull** [KnpLabs/snappy#430]
Hello, it look like you closed the issue [169](https://github.com/KnpLabs/snappy/issues/169) without a clear solution or at least to me there are workaround that not resolve the issue. 
I'm still experiencing this with snappy 1.2.1 and wkhtmltopdf 0.12.6 on Debian 10 server with Apache and php 7.3.
As the previous issue I can correctly generate the pdf in 2 seconds running the command from shell, if I run it with $snappy->generate doesn't matter the timeout it will only generate the pdf after it generate a ProcessTimedOutException. Again as in the issue 169 the problem exist with the cookie option,
`$snappy->setOption('cookie', array('PHPSESSID' => $cookie));`

I'm missing something? There are other way to render an Url with Snappy?

**Comment by SilverBull** [comment]
So apparently the repo is a bit stale or I'm the only one still with the problem.

**Comment by parapente** [comment]
@SilverBull I have also encountered the same problem using laravel sail container and using the same version of snappy and wkhtmltopdf. The container doesn't use apache to serve the pages so I don't think that is relevant to the problem. I can create pdfs just fine using wkhtmltopdf from the command line.
