### ISSUE TITLE
some css are not working image generation time

### ISSUE THREAD

**Issue by Akash-softnweb** [KnpLabs/snappy#431]
Issue when generating the HTML to Image
![image](https://user-images.githubusercontent.com/69900042/133446865-36a9a6e3-f823-4756-9dc3-a2896ae02976.png)

Html original response is 
![image](https://user-images.githubusercontent.com/69900042/133447130-f41f3e4d-ba0a-4ed4-b366-ea725627360b.png)

please how to i fix it 

        $options = [
            'images' => true,
            'cookie' => array(),
            'quality' => 1000,
            'width' => 1920,
            'height' => 1080
        ];
        

        $image = \App::make('snappy.image.wrapper');
        $image->loadHTML(html_entity_decode($this->slide->content));
        $image->setOptions($options);
        $image->setOption('enable-javascript', true);
        $image->setOption('javascript-delay', 5000);
        $image->setOption('no-stop-slow-scripts', true);
        $image = $image->output();

**Comment by alexpozzi** [comment]
Hello,
This is most probably an issue of wkhtmltopdf (or the version you are using) that does not support the CSS property you configured.
I guess you'll be luckier opening an issue on wkhtmltopdf repository but if I remember correctly, for example, flexbox is not still fully supported.

**Comment by alexpozzi** [comment]
It can also depends on the css not being accessible and I suggest you to manually run the wkhtmltopdf command enabling the verbose mode to see if you'll get more information.
