### ISSUE TITLE
Page size is longer than the actual size.

### ISSUE THREAD

**Issue by tes123id** [KnpLabs/snappy#432]
I have set up in css, in the html content, width and height according to A4 size in mm (210mm X 297mm) andi put a border css, to identifiy the area within.
the page-size option has been set also to A4 
i have set margin to 0.

but the result is the page height seem to be longer, so the content is floating.

so, how to get content apprear in full-size page ?

**Comment by alexpozzi** [comment]
Hello,
Can you provide an example to reproduce the problem, the expected result and also the result you get?
It would be useful to be able to help you faster.

**Comment by liuyong888** [comment]
> Hello, Can you provide an example to reproduce the problem, the expected result and also the result you get? It would be useful to be able to help you faster.



> Hello, Can you provide an example to reproduce the problem, the expected result and also the result you get? It would be useful to be able to help you faster.

#436
