### ISSUE TITLE
How to make it work on Windows

### ISSUE THREAD

**Issue by PeteYorn** [KnpLabs/snappy#44]
Hello guys

I've been trying to put Snappy to work on Windows (IIS) with no success.

What I've done:
- Installed wkhtmltopdf-0.9.9-installer.exe from http://code.google.com/p/wkhtmltopdf/downloads/list
- Downloaded snappy and copied the src folder to web folder.

My code:
<?php

require_once '/src/autoload.php';

use Knp\Snappy\Pdf;

$snappy = new Pdf('C:\\"Program Files"\wkhtmltopdf\wkhtmltopdf.exe');

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
echo $snappy->getOutput('http://www.github.com');

?>

Result:
Shows one pdf file to open or save, but it's corrupted.

P.S: In the command line wkhtmltopdf works well.

I'm doing something wrong?

Thanks in advance,
Pete

**Comment by FlorianBruniaux** [comment]
Have you solved the problem by changing the path ?

**Comment by FlorianBruniaux** [comment]
You should use : 
```php
$snappy = new Pdf();
$snappy->setBinary('C:\DEV\tools\wkhtmltopdf.exe');
```
It works for us

**Comment by pilot** [comment]
please download latest version from the http://wkhtmltopdf.org/downloads.html -> 0.12.2.1

for windows as usual binary file should be defined in like way

`binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""`

**Comment by zealfire** [comment]
I am using the latest version of binary file but  the pdf created always says "fail to open document"

**Comment by akovalyov** [comment]
In order to debug all the Windows-related issues here I have installed php with windows on VirtualBox.
Configuration: Windows 10 Technical preview x64
PHP 5.6.0 (installed via Microsoft Web components platform)
wkhtmltopdf - 0.12.2.2 x64 from their website

```php
<?php

require_once 'vendor/autoload.php';

use Knp\Snappy\Pdf;

$snappy = new Pdf('C://"Program Files"/wkhtmltopdf/bin/wkhtmltopdf.exe');

$snappy->generateFromHtml('<p>Hello <b>world</b></p>', 'test.pdf');
```

Everything works without any modifications.
if anybody can provide some testcases - I can try it, otherwise it can be closed IMO.

**Comment by Ugoku** [comment]
Installed Snappy and wkhtmltopdf through Composer. 
```
		$snappy = new Snappy\Pdf($'c:/wamp/projectname/vendor/bin/wkhtmltopdf-amd64');
		$snappy->generateFromHtml('<h1>Foo</h1><p>Bar</p>', 'test.pdf');
```
Does not work for me (error `The file 'test.pdf' was not created`). The reason is, running wkhtmltopdf (through Snappy or from the command line) just echoes the content of the wkhtmltopdf-amd64 binary, instead of running it.
This probably has nothing to do with Snappy, but posting here anyway for those experiencing the same thing. I haven't found a solution yet, will keep everyone updated.

**Comment by akovalyov** [comment]
It is exception of wkhtmltopdf, source - https://github.com/wkhtmltopdf/wkhtmltopdf/blob/5f89404e4d67c513feb1d9932609e4cbda2d708d/src/lib/imageconverter.cc#L221

Please, check your images.

**Comment by Ugoku** [comment]
What images? :) the code above was all I had and it triggered that error.

I've got it working now though, now sure what has changed...

**Comment by vincentkedison** [comment]
```
return array(


    'pdf' => array(
        'enabled' => true,
        'binary'  => 'C://"Program Files"/wkhtmltopdf/bin/wkhtmltopdf.exe',
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary'  => 'C://"Program Files"/wkhtmltopdf/bin/wkhtmltopdf.exe',
        'timeout' => false,
        'options' => array(),
        'env'     => array(),
    ),


);
```
This works for me :)

**Comment by stevebauman** [comment]
For anyone else visiting this issue as well, developing on Windows 10 64-bit with Laravel and installing the following package [wemersonjanuario/wkhtmltopdf-windows](https://github.com/wemersonjanuario/wkhtmltopdf-windows) I was able to get up and running pretty quick! Here's the config:

```php
return [
    'pdf' => [
        'enabled' => true,
        'binary'  => base_path('vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf.exe'),
        'timeout' => false,
        'options' => [

        ],
        'env'     => [],
    ],

    'image' => [
        'enabled' => true,
        'binary'  => base_path('vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltoimage.exe'),
        'timeout' => false,
        'options' => [],
        'env'     => [],
    ],
];
```

Make sure you edit the path depending on whether you're running 64/32 bit Windows.

**Comment by WhereJuly** [comment]
This worked for me under Laravel 5.8 and WAMP local development environment (surely on web server there should be Linux binary in place of Windows' `exe` file):
```
use Knp\Snappy\Pdf;

$snappy = new Pdf('D:/your/path/to/exe/no/spaces/wkhtmltopdf.exe');
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="file.pdf"');
return $snappy->getOutputFromHtml('<h1>Bill</h1><p>You owe me money, dude.</p>');
```

The culprit was spaces in the path. After `wkhtmltopdf.exe` [installation](https://wkhtmltopdf.org/downloads.html) I just copied the `exe` to the convenient no-space path folder.

**Comment by FVolral** [comment]
It worked for me simply using this path : 
`define('__PATH_TO_WKHTMLTOPDF__', 'C://Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe');`

**Comment by rick-nataniel-walker** [comment]
I am running the same problem for days now, i don't what i am doing wrong but i tried to change paths to the bin too many times before. What i get is the conversion from a certain website when i use `echo $snappy->getOutput('https://github.com/KnpLabs/snappy/issues/104');` but to convert HTML i get nothing but a non created PDF error.

I installed Snappy with composer and the I had to include the .exe file in my working directory to at least have website converted

This is my code:
`require __DIR__ . '/vendor/autoload.php';
  use Knp\Snappy\Pdf;

  $snappy = new Pdf('wkhtmltopdf.exe');
  header('Content-Type: application/pdf');
  echo $snappy->generateFromHtml('<h1>hello world</h1>','file.pdf');`

**Comment by JhonatanRaul** [comment]
This problem happens to me.
I debugged `Snappy\AbastractGenerator.php` and it is generating the `.pdf` file in my temp directory but is not copying it to the destination directory. :[

**Comment by alexpozzi** [comment]
@JhonatanRaul can you give a little bit more information regarding the issue (error logs) and your configuration/code?
With this little information it's difficult to help.
