### ISSUE TITLE
How to use Image.php?

### ISSUE THREAD

**Issue by uponup** [KnpLabs/snappy#446]
`
$snappy = new Image('/usr/local/bin/wkhtmltopdf');
$snappy->generateFromHtml($html, 'test.jpg', [], true);
`
There is error encounted:

Fatal error: Uncaught RuntimeException: The exit status code '1' says something went wrong:
stderr: "Unknown long argument --format

Name:
  wkhtmltopdf 0.12.6 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

**Comment by uponup** [comment]
SOS

**Comment by alexpozzi** [comment]
Hello,
I think that the problem is that you are using the wrong binary. Please try with `/usr/local/bin/wkhtmltoimage`.
