### ISSUE TITLE
wkhtmltopdf

### ISSUE THREAD

**Issue by GuigZ-** [KnpLabs/snappy#456]
Hey people,

I've a problem with your lib.
In fact, wkhtmltopdf is not supported since Alpine3.15

> QtWebKit was removed due to lack of upstream support
qt5-qtwebkit, kdewebkit, wkhtmltopdf, and py3-pdfkit have been removed due to known vulnerabilities and lack of upstream support for qtwebkit. Other programs have been adjusted to use qt5-qtwebengine where appropriate. The most direct replacement for wkhtmltopdf is weasyprint, which is available in the Alpine Linux community repository. puppeteer and pandoc are also options, depending on your needs. See [#12888](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12888) for more information.

Do you work for a new binary system ? like weasyprint ?

**Comment by allanlaal** [comment]
current workaround is to composer require prebuilt binariers for ubuntu and debian:
		"lissonpsantos2/wkhtmltopdf-amd64": ">0.12.5",
		"lissonpsantos2/wkhtmltoimage-amd64": ">0.12.5",

**Comment by GuigZ-** [comment]
I think that this lib answer developper to make choice in a configuration to chose the good binaries or system to create pdf

**Comment by AntoineLelaisant** [comment]
We are currently considering a rewrite of Snappy to be able to use other backends than wkhtmltopdf. Feel free to contribute to this discussion https://github.com/KnpLabs/snappy/discussions/467 if you have any feedback or concern.

**Comment by AntoineLelaisant** [comment]
Closing this issue as this discussion in favor of #467 🙂
