### ISSUE TITLE
Uncaught exception on start

### ISSUE THREAD

**Issue by yekver** [KnpLabs/snappy#46]
Getting an error while trying to execute this code:

``` <?php
require_once 'src/autoload.php';
use Knp\Snappy\Pdf;
$snappy = new Pdf('/var/www/seos/bin/wkhtmltopdf-amd64');
$snappy->generateFromHtml('<h1>Bill</h1><p>You owe me money, dude.</p>', 'bill-1233.pdf');
```

**Error message:**
Fatal error: Uncaught exception 'RuntimeException' with message 'The file 'bill-1233.pdf' was not created (command: /var/bin/wkhtmltopdf-amd64 --lowquality '/tmp/knp_snappy50c77c04ba9bf1.73763694.html' 'bill-1233.pdf').' in /var/www/htdocs/src/Knp/Snappy/AbstractGenerator.php:261 Stack trace...

**Comment by the-pupz** [comment]
[Mon Nov 23 13:33:42.737050 2015] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The file 'test.png' was not created (command: C:\\wamp\\www\\composer/vendor/bin/wkhtmltoimage-amd64 --format "jpg" "C:\\Windows\\TEMP\\knp_snappy565331d52657a7.49044374.html" "test.png").' in C:\\wamp\\www\\composer\\vendor\\knplabs\\knp-snappy\\src\\Knp\\Snappy\\AbstractGenerator.php:308\nStack trace:\n#0 C:\\wamp\\www\\composer\\vendor\\knplabs\\knp-snappy\\src\\Knp\\Snappy\\AbstractGenerator.php(153): Knp\\Snappy\\AbstractGenerator->checkOutput('test.png', 'C:\\wamp\\www\\com...')\n#1 C:\\wamp\\www\\composer\\vendor\\knplabs\\knp-snappy\\src\\Knp\\Snappy\\AbstractGenerator.php(170): Knp\\Snappy\\AbstractGenerator->generate(Array, 'test.png', Array, false)\n#2 C:\\wamp\\www\\composer\\teste.php(12): Knp\\Snappy\\AbstractGenerator->generateFromHtml('<p>Hello <b>wor...', 'test.png')\n#3 {main}\n  thrown in C:\\wamp\\www\\composer\\vendor\\knplabs\\knp-snappy\\src\\Knp\\Snappy\\AbstractGenerator.php on line 308

i guess this is the error that he tried to put here, having samu issue here, WAMP Server running in Windows 7. HELP???

**Comment by akovalyov** [comment]
@the-pupz you are trying to use Linux Debian package for x64 systems. You should use .exe files for Windows. You can check out `suggests` section of Snappy - https://github.com/KnpLabs/snappy/blob/master/composer.json#L30.

**Comment by docteurklein** [comment]
@the-pupz try to execute the same command from your command line:

- start a windows command prompt
- copy paste the command displayed in the error message

If same error, it's not a snappy problem but a wkhtml one

**Comment by the-pupz** [comment]
thx buddies... will try right now and post here the results

**Comment by the-pupz** [comment]
just one more question: is the wkhtmltoimage out for windows users? i cant found it in suggests secction
