### ISSUE TITLE
Error while installing wkhtmltopdf-amd64 via composer

### ISSUE THREAD

**Issue by vineeth030** [KnpLabs/snappy#463]
I tried to install wkhtmltopdf-amd64 via composer with following command

> composer require h4cc/wkhtmltopdf-amd64 0.12.x

but the installation failed in middle with following error.

````
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update h4cc/wkhtmltopdf-amd64
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking h4cc/wkhtmltopdf-amd64 (0.12.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading h4cc/wkhtmltopdf-amd64 (0.12.4)
  - Installing h4cc/wkhtmltopdf-amd64 (0.12.4): Extracting archive .........................................
  ............................................................................................................................................................................
  ............................................................................................................................................................................
  ............................................................................................................................................................................


In PackageManifest.php line 122:

  Undefined index: name

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
````

Additional details:

I am trying to install this on a Plesk server. This is a laravel project, I am trying to install laravel-snappy with following guides:
https://github.com/barryvdh/laravel-snappy
https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies

Following are the details of server:

````
CPU: Intel Core Processor (Broadwell) (8 core(s))
Version: Plesk Obsidian v18.0.20_build1800200114.18 os_CentOS 7
OS: CentOS Linux 7.8.2003 (Core)
````

Please help if anyone knows how to resolve this issue.

**Comment by AntoineLelaisant** [comment]
Sorry for the delay of this answer but this issue seems to be related to `h4cc/wkhtmltopdf-amd64` or the `barryvdh/laravel-snappy` and not Snappy directly. 

Did you manage to find a solution to your issue tho ? 

I'm closing the issue since this is apparently not an issue with snappy. Feel free to reopen the issue if there is something we miss.

**Comment by vineeth030** [comment]
This was an issue related to composer vs laravel version confict. Older laravel not supporting Composer 2.0 udpate. I have fixed this. Thanks for responding and closing this issue.
