### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [KnpLabs/snappy#492]
Symfony 3 and 4 are at EOL, I think it's reasonable to only support 5.4+, or at least drop 3.4 support.

Also, shouldn't these be ^ and not ~?  

```
"symfony/process": "~3.4||~4.3||~5.0||~6.0",
```

**Comment by garak** [comment]
Old Symfony versions are already dropped in the v2-unstable branch.
I agree about supporting Symfony 7, which should be easy.

**Comment by tacman** [comment]
Hmm, I guess we need to make v2 stable!

**Comment by alexpozzi** [comment]
Closed by https://github.com/KnpLabs/snappy/releases/tag/v1.5.0
