### ISSUE TITLE
Generate PDF file without outputting

### ISSUE THREAD

**Issue by ghost** [KnpLabs/snappy#58]
Using Laravel 4 with wkhtmltopdf installed via Homebrew.

Is it possible to generate the pdf and store it without doing anything further?

This would be really useful where other non-snappy processing needs to take place. E.g Creating a pdf file, then creating some other project files. Zipping them up and then I can output the zip file myself for download.

**Comment by webdevilopers** [comment]
Still checking the port problem. Any help would be appreciated!
Feel free to follow my steps on my gist:
https://gist.github.com/webdevilopers/e0d34a1c04ef2050a450

**Comment by docteurklein** [comment]
I don't think the address, or the port, have anything to do with this.
If you use the built-in server, you can try to serve assets with a second server, hosted on localhost:8001 for example.

Configure your assets urls to point there, and try again.
The result is that the 2 built-in servers will not block each others requests. 

A better solution is to use a real http server :)

**Comment by webdevilopers** [comment]
Thanks for the tip, @docteurklein . i moved my assets to port **8001**.
The PDF will be generated and shows the images.
As soon as I switch back to the **8000** port for generating and assets I get the **timeout** again.

Since our prodution server isn't running yet this is my only way to test it.
But this is not a normal behaviour, right?

Is it an issue with `wkhtmltopdf` or my environment?

**Comment by docteurklein** [comment]
Im not sure of what's happening on your machine,

but I guess: no, it's a problem only with the php built-in server.

If you serve assets **and** the pdf on the same server, the first request will block others.
Which is really problematic because the first request needs the next requests to finish in order to return correctly :)

It's the snakes who bites its own tail :)

there is no problem with wkhtmltopdf nor snappy.
Only your http server.

**Comment by barryvdh** [comment]
Better use a real webserver for production, like vagrant or *amp :)

**Comment by webdevilopers** [comment]
You are right, @docteurklein and @barryvdh !
Indeed the PHP built-in web server is single threaded and that's why I got the timeout:
http://stackoverflow.com/questions/25062398/max-concurrent-connections-for-phps-built-in-development-server

It should work on a regular production machine.

**Comment by Wayne-Wen** [comment]
I have do some search for this issue, and still have no idea what cause this problem. In my case, our production server can generate the pdf file, but sometimes, there are timeout error as reported by laravel. I believe that it is not PHP built-in web server. Is it an issue with wkhtmltopdf?

**Comment by docteurklein** [comment]
@Wayne-Wen what server are you using when timeouts occur? the built-in php server?
If so, try with apache/nginx/whatever, and look if it behaves the same.

**Comment by Wayne-Wen** [comment]
@docteurklein We are using apache server for dev and production. In our local env, everything is good. However, when it goes to real server, the issue comes up.

**Comment by docteurklein** [comment]
Interesting. If you look at the apache access logs, do you notice something odd?
like maybe a first request comes, then a second, but first blocks?

**Comment by Wayne-Wen** [comment]
From the log file, The second request come 30 sec after the first request on the same file. I think 30 sec is enough for first request to complete.

**Comment by BrownSim** [comment]
I have had the same trouble, i fixed it by deleting my css link
Don't know why, but it works

**Comment by osaris** [comment]
Same issue here using Apache2 on Windows. Works fine locally on my mac. 

If I remove the CSS it works fine. CSS link is generated with full path and can be curled without problem from the server. The html and PDF files are generated but never sent to the browser (timeout).

**Comment by akovalyov** [comment]
CSS file also can contain links to different resources (images/fonts), which should be downloaded.

**Comment by BrownSim** [comment]
I solved it by passing my css in relative path.
On my online version, i use https, on my macos version, it's http.

**Comment by osaris** [comment]
@akovalyov good point but I'm using bootstrap (which have dependencies) and my own CSS file (only few lines of CSS, no dependency) and If I remove only bootstrap the problem is the same.

@BrownSim thanks, I'll try that

**Comment by osaris** [comment]
@BrownSim can't get it working, If i use relative path and display the HTML view, everything is ok but when rendering PDF the CSS is not applied.

**Comment by BrownSim** [comment]
I think it's because when the pdf is created, the path is not the same as when you display it into a PDF view 
The base path when you create the pdf is from wkhtmltopdf.

**Comment by osaris** [comment]
@BrownSim make sense so it's not a good solution for me.

**Comment by BrownSim** [comment]
I use __DIR__/your_path_to_css on my case
The css works on a modal window and when I rendering PDF. If I understand it's why you need ?

**Comment by osaris** [comment]
Not beautiful but it's a good workaround for me, I'm using the ```user-style-sheet``` options of workhtmltopdf in snappy configuration file to load my CSS.

**Comment by khalilst** [comment]
I have timeout issue as @barryvdh mentiond in Laravel 5.5 and barryvdh/laravel-snappy.
`"/wkhtmltox/bin/wkhtmltopdf --lowquality --margin-left '1' --margin-right '1' --orientation 'landscape' '/tmp/knp_snappy5a014503a4e735.42351694.html' '/tmp/knp_snappy5a014503a4f0a7.39978077.pdf'" exceeded the timeout of 60 seconds.`

But using absolute path solved this timeout issue. Thanks to @BrownSim 
For laravel people:
`public_path('/css/example.css')`

**Comment by tarhe** [comment]
I got this solved when I set:

$pdf->setTimeout(10000);
$pdf->setOption('lowquality', true);

I also noticed that after setting $pdf->setOption('lowquality', true);, the pdf file generates in 5 - 10 seconds instead of 1+ minute.
