### ISSUE TITLE
cannot execute binary (on Mac OS X)

### ISSUE THREAD

**Issue by misterlami** [KnpLabs/snappy#59]
I get this error when below code runs

**_The file '/var/tmp/knp_snappy51db03691aa540.12804579.pdf' was not created (command: [site-dir]/vendor/google/wkhtmltopdf-i386/wkhtmltopdf-i386 --lowquality 'http://www.github.com' '/var/tmp/knp_snappy51db03691aa540.12804579.pdf')._**

``` php
$snappy = Helper::snappyPdf(); #this just returns snappy pdf object
echo $snappy->getOutput('http://www.github.com');
```

So I tried running wkhtmltopdf as sudo from command line (below code) and got a **_cannot execute binary_** error

```
[site path]/vendor/google/wkhtmltopdf-i386/wkhtmltopdf-i386 --lowquality 'http://www.github.com' '/var/tmp/knp_snappy51db03691aa540.12804579.pdf'
```

FYI I tried both 32 and 64 bit binaries and I installed wkhtmltopdf using composer

**Comment by whitehorse55** [comment]
in my opinion chmod 777 <filename>

**Comment by omarjavierr277** [comment]
en mi caso era el problema de compatibilidad y cambie en la configuración en el mac m1

/usr/local/bin/wkhtmltoimage
/usr/local/bin/wkhtmltopdf

'binary' => '/usr/local/bin/wkhtmltopdf',
