### ISSUE TITLE
For "wkhtmltoImage": is possible add functions/url at the param "'run-script'"?

### ISSUE THREAD

**Issue by Lobon18** [KnpLabs/snappy#72]
Hi! 

First off all, congratulations for your "library", is great!!  ;-D

I have been studying the params relationated with "wkhtmltoImage", and one of the params is --run-script, but you only can add js code directly.

Is there any posibility (or do you know) of adding a URL of a 'file.js' in order to create functions or more code in a separated file (like the '-user-style-sheet' param)?

At the moment, I have checked that you can only add js code in one line, and it's a problem if you want to add more code :-(
- I'm using the libwkhtmltox-0.11.0_rc1.zip (Win) and I'll install it in Linux too.

Thank you very much in advance!
Regards,

**Comment by NiR-** [comment]
AFAIK it's not possible to provide a URL for this option, even in latest versions. Closing because this is not related to snappy itself.
