### ISSUE TITLE
Command Errors handling

### ISSUE THREAD

**Issue by ogizanagi** [KnpLabs/snappy#90]
Got an `Uncaught PHP Exception RuntimeException: "The exit status code '1' says something went wrong` when `Warning: Failed loading page` even with the  `--load-error-handling ignore`. The pdf is correctly generated from the command, but cannot be displayed immediatly after generation because of this RuntimeException. (This is provocated when any asset cannot be loaded (404 for instance)).

This is due to the `checkProcessStatus` method from  `Knp\Snappy\AbstractGenerator` class, which is only checking if status code === 0.

Catching the Exception isn't enough to get output, since tmp file content isn't retrieved before. Cannot we let the choice to retieve or not the errors and display the pdf by : 
- Catching excption internally (`generate` method)
- Populating an errors array
- Giving the possibility to add the errors array to `getOutput($input, array $options = array())` method as reference

So it will result to : 

``` php

public function getOutput($input, array $options = array(), array &$errors = array())
 {
       $filename = $this->createTemporaryFile(null, $this->getDefaultExtension());

       try {
            $this->generate($input, $filename, $options);
        } catch(RuntimeExcpetion){
            //Populates $errors
        }

        $result = $this->getFileContents($filename);

        $this->unlink($filename);

        return $result;
 }

```

Idem for LoggableGenerator from KNPSanppyBundle.

**Comment by fhferreira** [comment]
+1 I've changed like @barryvdh said up. Change the vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php to accept exitcode "1" and the PDF is generated.

**Comment by NiR-** [comment]
Pretty old issue...

> Got an Uncaught PHP Exception RuntimeException: "The exit status code '1' says something went wrong when Warning: Failed loading page even with the --load-error-handling ignore

This is not a normal behavior from wkhtmltopdf. If you ever encounter such error it should be reported to wkhtml. Note that you might face it if you have query string in URLs of failing medias ([see here](https://github.com/wkhtmltopdf/wkhtmltopdf/commit/333521a51bf53ba632f3281a73fd14091c3ab250)).

Thus I think this workaround shouldn't be implemented.
