### ISSUE TITLE
The process has been signaled with signal "5".

### ISSUE THREAD

**Issue by mgomez-dgt** [KnpLabs/snappy#94]
Warning: file_put_contents(/var/folders/xs/80v35bxd2xnbr36jq93qcl6m0000gn/T/knp_snappy53874552c8f521.74433518.html): failed to open stream: Permission denied in .....

~/bin/wkhtmltopdf/wkhtmltopdf --lowquality '/var/folders/xs/80v35bxd2xnbr36jq93qcl6m0000gn/T/knp_snappy53874552c8f521.74433518.html' '~/web/uploads/pdf/export_backgroundcheck_2014_05_29_09_33_52.pdf'

**Comment by thisistouhid** [comment]
getting the same error. The same code (command) works fine on terminal. I m using mac. 
Shouldn't it (wkhtmltopdf) be using /temp directory instead of /var/folders/....  How do i solve the problem?
